meetup/meetup-web-components

.npmignore
.npmrc
.travis.yml
Makefile

no need to 'dynamically' update `.npmrc`. You can't publish from your local machine without an `NPM_TOKEN` env variable, but we never publish from local machines anyway

Read from env var for all npm publishing

---

.npmrc
.travis.yml

This update removes the `NPM_TOKEN` reference from all git branches, but _will_ commit a reference to it in the tagged releases. In practice, we shouldn't ever see the modified `.npmrc`, but it is technically in our git repo in a headless commit - just the env var name, not the value, so no security concern

git commit npmrc during Travis build but don't push

---

package.json
src/avatar.story.jsx
src/avatarmember.story.jsx
src/avatarmember.test.js
src/datedisplay.test.js
src/groupcard.story.jsx
src/groupcard.test.jsx

Use the `meetup-web-mocks` repo, and upgrade sassquatch2 to avoid dependency warnings.
Fixes #14 
Fixes https://meetup.atlassian.net/browse/WC-9

Use mocks repo and upgrade sassquatch

---

jest.config.json
src/Modal.jsx
src/modal.story.jsx
src/modal.test.js

The modal component needs to be added to MUG Comm. This PR breaks out that component from responsify land so that we can use it in mup-web. The goal was to keep this component as "dumb" as possible so we are passing in a dismiss handler rather than handling dismissal within the component.

Break out Modal component from responsify

---

assets/scss/main.scss
assets/scss/popover.scss
src/Popover.jsx
src/Tabs.jsx
src/popover.story.jsx
src/popover.test.jsx
src/tabs.test.jsx
src/utils/bindAll.js

(marking prelim until tests are complete)
Popover menu component (wraps links into a drop down menu activated by a button)

Wc 7 popover component

---

src/TabsTab.jsx

We are using other proptypes for labels like formatMessage, making list of acceptable labels more flexible.

WC-25: TabsTab - adding other proptypes for labels

---

src/Avatar.jsx
src/avatar.test.js

Fixes https://meetup.atlassian.net/browse/WC-28
This PR checks whether `href` or `to` props are passed into the component and conditionally returns a `<a>` or `<span>` element. This should fix the problem of not being able to click a `<span>` element in `mup-web`.
Adding the Prelim tag until I confirm this works on `mup-web`.

Fix Avatar links

---

assets/scss/_popover.scss

This fixes a bug where indirect children of `.popover-menu-option` were being unintentionally styled as options.

use direct child selectors for popover option children styling

---

assets/scss/_popover.scss

Fixes https://meetup.atlassian.net/browse/MUP-7694
The popover menu had a weird padding on _some_ screens. Removing this overflow style attribute seemed to do the trick, but I'm not sure why. After chatting with @akdetrick, this attribute might have been unintentional, so I don't see the harm in removing it.

Remove popover overflow style

---

src/Tabs.jsx

If you pass in a `<Link` component in the `tabs` prop, the `<Link` will not be rendered; only its children. This PR will allow the entire component to render.

fully render each tab instead of just the children of the component

---

package.json

None of the MWC components use `<Link>`, so it doesn't need to be a peer dependency. Eventually we'll probably want something like Avatar to be able to use a within-app `<Link>`, but until then, there's no need for the peer dep.

Remove React Router peer dep

---

package.json
yarn.lock

Update to `swarm-sasstools` `1.0.9`; change to devDependency for easier management in client apps

make sasstools a dev dependency; update to 1.0.9 for webpack2

---

src/TextInput.jsx
src/textInput.story.jsx

Fixes https://meetup.atlassian.net/browse/SDS-204
We want errors to be able to be FormattedMessages.

Sds 204 textinput errors

---

src/modal.test.js
src/stripe.test.jsx
src/utils/testUtils.js

We want to minimize the number of dependencies that the meetup-web-mocks repo has, so we're going to have each consumer repo maintain it's own testUtils.jsx.

Copy testUtils from mocks repo into compenents repo

---

.travis.yml

Primary motivation is to avoid 502 errors but it will be interesting to see if there are build perf improvements.

cache yarn and node modules

---

src/TextInput.jsx
src/textInput.test.jsx

DoD:
- Adding onChange prop so outside React components can get updates as input changes
- Adding a `getValue` function for form submissions

Adding onChange prop for TextInput

---

assets/scss/components/_all.scss
assets/scss/components/_inlineblockList.scss
src/InlineBlockList.jsx
src/inlineBlockList.story.jsx
src/inlineBlockList.test.jsx

Needed for header and footer navigation redesign for replatform
Takes an array of text strings or elements and creates a list that is displayed inline

InlineBlockList component

---

src/SectionTitle.jsx

I'm seeing this issue when trying to use `<SectionTitle title='Members' />`:
```
Warning: Failed prop type: Invalid prop `title` of value `Members` supplied to `SectionTitle`, expected one of [null,null].
in SectionTitle (created by Search)
in Search (created by Form(Search))
in Form(Search) (created by Connect(Form(Search)))
in Connect(Form(Search)) (created by ReduxForm)
in ReduxForm (created by MembersContainer)
in div (created by MembersContainer)
in MembersContainer (created by Connect(MembersContainer))
in Connect(MembersContainer) (created by RouterContext)
in div (created by PageWrap)
in PageWrap (created by AppContainer)
in IntlProvider (created by AppContainer)
in AppContainer (created by Connect(AppContainer))
in Connect(AppContainer) (created by RouterContext)
in RouterContext …
```

oneOf should be oneOfType

---

src/Tabs.jsx

null children error occurring when a check lives with a <Tab> component that results in a child not being rendered
e.g. of when error occurs
<Tab>
{something && <TabsTab />}
</Tab>

adding check for null children

---

src/PageHead.jsx
src/pageHead.story.jsx
src/pageHead.test.jsx

Fixes https://meetup.atlassian.net/browse/MW-739
Adds a label above the title in PageHead
**NOTE:** small-caps (English-only) coming with a sasstools fix from @akdetrick

Add optional label to PageHead

---

assets/scss/components/_dateTimePicker.scss
src/CalendarComponent.jsx
src/DateTimePicker.jsx

- fix style dependency on flatpickr
- flatpickr depends on dom, which breaks on server-side rendering in mup-web. remove dom-dependent aspects of datetimepicker.
- profit
https://meetup.atlassian.net/browse/SDS-226

DateTimePicker render should not depend on DOM; fix 3rd party CSS import

---

package.json

Moves the `base64-image-loader` package to `dependencies` from `devDependencies`. I believe this will prevent a missing module problem when using `Avatar` in other repos, but could use confirmation from someone more familiar with Yarn

use dependency instead of devDependency for base64-image-loader

---

assets/scss/components/_groupCard.scss

Avoids a Safari paint performance problem. This slightly darkens the text protection gradient in place of the desaturate and contrast filters.

remove CSS filter from groupCard styles

---

src/Modal.jsx
src/modal.test.js

When testing the experience of the modal in `mup-web` on small screens, the "snapped" modal (snaps to the edges of the viewport) isn't positioned correctly with the scroll.
When the viewport is small, we should set the `margin-top` of the modal to match the exact scroll position for a better experience.
See updated tests for a detailed view of new requirements.

Update getModalPosition & tests for updated product requirements

---

assets/scss/components/_button.scss
src/forms/button.story.jsx

Fixes https://meetup.atlassian.net/browse/SDS-193
Sets default `button` hover color in inverted context to secondary inverted text on hover.

fix default button hover in inverted

---

assets/scss/components/_button.scss

This change removes the default `.button` padding from the `button--reset` variant. 
This change fixes alignment issues like this:
If extra padding is needed on a `button--reset`, engineers can add `padding--[direction]` modifier classes as needed.

kill default padding in button--reset

---

assets/scss/components/_modal.scss
assets/scss/components/_stripe.scss
src/interactive/Modal.jsx
src/interactive/modal.story.jsx
src/interactive/modal.test.js

Fixes https://meetup.atlassian.net/browse/WC-35
https://meetup.atlassian.net/browse/MW-814
Some modals, like the RSVP success modal, are designed to have a full bleed hero header

Hero headers into Modals

---

src/layout/InlineBlockList.jsx

Fixes bad proptype validation that was causing this error:
```
Warning: Failed prop type: Invalid prop 'items' of value '[object Object],[object Object],[object Object]' supplied to 'InlineBlockList', expected one of [null,null].
```

fix inlineblocklist prop types

---

assets/scss/components/_inlineblockList.scss

🎼 
Don't speak
Screen-readers know what you're saying
So please stop conveying
CSS content 'cause it hurts
Hush, hush don't read these glyphs 'cause it hurts
🎶

instruct screen readers not to speak separator glyphs in inlineblocklist

---

assets/scss/components/_section.scss
src/layout/section.story.jsx

Removed weird :last-child magic to make `<Section>` behavior less mysterious

Simplify Section styles

---

assets/scss/components/_section.scss
src/layout/Section.jsx
src/layout/section.story.jsx
src/layout/section.test.jsx

`noBorder` sounds like all it does is remove the bottom border - `className='border--none'` is better for that
What we actually want is to remove the bottom border _and_ the bottom padding. This is useful when working with 2 columns of `<Section>`s that stack at mobile

Rename noBorder prop in Section

---

src/layout/Section.jsx

PR feedback for upgrading layout components in [mup-web](https://github.com/meetup/mup-web/pull/1007)
noSeparator prop can be a boolean or one of the breakpoints

Section noSeparator proptype fix

---

assets/scss/components/_button.scss

Fixes https://meetup.atlassian.net/browse/SDS-280
Helps with https://meetup.atlassian.net/browse/MW-1027
Removes height and border-radius from buttons with the `reset` prop to truly "reset" buttons.

Reset more styles on button reset

---

assets/scss/components/_button.scss

Fixes https://meetup.atlassian.net/browse/SDS-286
Will help with: [MW-1023](https://meetup.atlassian.net/browse/MW-1023) and [MW-1027](https://meetup.atlassian.net/browse/MW-1027)
Just reducing padding coming from `.flex-item`. The CSS selectors to do this without making changes to `Button` aren't ideal

Reduce spacing in icon buttons

---

src/interactive/Modal.jsx
src/interactive/modal.story.jsx
src/interactive/modal.test.js

https://meetup.atlassian.net/browse/MUP-10807
We've been tasked with adding a modal that doesn't have a close area at the top. This change allows the Modal component to accept a `closeArea` prop that can determine whether the close area is displayed or not. The default behaviour does not change when the `closeArea` prop is omitted (the close area displays by default)

make the modal close area toggleable

---

assets/scss/components/_all.scss
assets/scss/storybook.scss

Color mappings were only imported to storybook, not usable by all component CSS in other projects

Bug fix - changed where color-mappings are imported

---

Makefile
README.md
assets/scss/components/_all.scss
assets/scss/components/_icon.scss
package.json
src/media/Icon.jsx
src/media/icon.story.jsx
src/media/icon.test.jsx
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-50
**Support for `swarm-icons` icon set redesign.** The `Icon` component will now append `--small` to shape names when using `xs` size in order to support small icon variants. We've also moved base icon styles into this repo.
**From storybook:**
**Overview of design changes in `swarm-icons` `1.0.0`**

Wc 50/icon shape variant support

---

package.json

The previous yarn-upgrade branch updated the `swarm-icons` dependency, but not the peerDependency version. Fixing here

uprade swarm-icons peer dependency version

---

src/media/Icon.jsx
src/media/icon.test.jsx

The `meetup-m` logo icon uses the same path for all sizes. This branch introduces a whitelist that excludes both `meetup-m` and `external-[service]` icons from small variants.

exclude `meetup-m` from using a `--small` variant shape

---

src/forms/NumberInput.jsx
src/forms/numberInput.test.jsx

This PR fixes some issues with the `NumberInput` component. We don't want to support `e` or `E` input values, we want to trigger `onChange` whenever the plus or minus signs get triggered, and we want to display the default value prop.
Fixes https://meetup.atlassian.net/browse/MW-1153

Number Input - Minor fixes

---

src/forms/Textarea.jsx
src/forms/textarea.test.jsx

Fixes https://meetup.atlassian.net/browse/MW-1356
This PR fixes a bug where the textarea doesn't resize on form submission. This is because the autosize library only listens to onChange events and not value changes.

Textarea - Update autosized height on changed values

---

assets/scss/components/_flex.scss

Fixes https://meetup.atlassian.net/browse/WC-63
Changes `-ms-preferred-size` from `0px` to `auto` for column-oriented flexbox; prevents height calculation bug in IE11 where flex items were collapsing when in column orientation.
The `-ms-preferred-size` is the IE version of `flex-basis`. Width calculation from a basis of `0px` is fine, but IE11 has issues with flex child height inside an indeterminate height container. This change is limited to `column` oriented flex children.

set flex basis for IE to auto

---

src/interactive/Popover.jsx
src/interactive/popover.story.jsx
src/interactive/popover.test.jsx

Fixes https://meetup.atlassian.net/browse/MW-1386
To close the Popover when a user clicks outside of it, Popover was using a `setTimeout` `0` because most browsers set the `document.activeElement` to `body` for an instant before reporting the actual focused element. **Safari is not most browsers**. 
A more stable approach is to attach a click listener to `body` on component mount ala `Dropdown`.

use body click listener instead of blur event to avoid Safari issue

---

assets/scss/components/_stripe.scss
src/interactive/Modal.jsx
src/interactive/modal.story.jsx
src/interactive/modal.test.js
src/layout/Stripe.jsx
src/layout/stripe.story.jsx
src/layout/stripe.test.jsx
yarn.lock

Fixes https://meetup.atlassian.net/browse/SDS-324
Adds a prop to `<Stripe>` and `<Modal>` (for the hero header) that allows engineers to hide the text protection scrim that used to automatically get added to a `<Stripe>` that has `backgroundImage` prop.
**This is a breaking change**, because any `<Stripe>` that has a `backgroundImage` prop but not an `inverted` prop will show black text and icons on top of the image and scrim.
This issue came up while building the [Event Home preview page](https://www.meetup.com/account/preview/).

Optionally hide text-protection scrim on Stripes with bg img

---

src/forms/TextInput.jsx
src/forms/textInput.test.jsx
src/utils/testUtils.js
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-70
related to  https://meetup.atlassian.net/browse/WC-69
Lets make our inputs and form fields PureComponents. This way they will play well with Redux forms in the app as well.

Wc 70 textinput pure component

---

assets/scss/components/_gridList.scss
src/layout/GridList.jsx
src/layout/gridList.story.jsx
src/layout/gridList.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-348
Sometimes we need gridlist items to be the same height. This PR lets you use flexbox for gridlist layout. This came from Chris' designs for showing a sample of members in cards on group home.

Added the ability to keep grid item heights consistent

---

package.json

For consistency between SDS projects, we're going to run any doc publishing scripts through a `yarn run publish-docs` command.

change task command to `publish-docs`

---

assets/scss/components/_popover.scss
src/interactive/popover.story.jsx

Fixes https://meetup.atlassian.net/browse/SDS-346
Changed popover to use min and max width to avoid weird text wrapping

Popover menu item text wraps too easily

---

src/media/Icon.jsx
src/media/icon.story.jsx
src/media/icon.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-365
Sets SVG fill color without depending on CSS. This issue came up during Group Home development - Kristin could have used the `<Button>` component to render the social media buttons at the bottom of the description if we had a way to color icons.
I think this PR in combination with a JS distribution of color values from `swarm-constants` could help us reduce CSS bloat - but I'd love to hear if anybody disagrees with this approach :)

Set Icon fill color on without adding CSS

---

assets/scss/components/_popover.scss

Fixes https://meetup.atlassian.net/browse/SDS-366
Added borders between menu items in popovers

Added borders between menu items in popovers

---

Makefile
package.json
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-76
Updates `swarm-sasstools`, which pulls colors from `swarm-constants` instead of `meetup-swatches`.
Marked as a **breaking change** because consumer apps may need to remap some older swatches color var names to new standard colors from `swarm-constants`.

Wc 76/update sasstools new colors

---

src/forms/SelectInput.jsx
src/forms/__snapshots__/selectInput.test.jsx.snap
src/forms/selectInput.test.jsx

Fixes https://meetup.atlassian.net/browse/MW-1726
This PR adds a check in the custom prop validator for the `value` prop if it is defined before throwing an error. This cleans up a error in the browser console when that prop is not provided.

SelectInput - Cleans up error when value not provided 🎪

---

assets/scss/components/_button.scss
assets/scss/util/_vars.scss
src/forms/Button.jsx
src/forms/button.story.jsx
src/forms/button.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-374
Added a variant to <Button> that provides a background and light grey border. We've been seeing this style used on event and group home, typically for buttons that are on top of a the light grey (#f5f6f7) background.

Added bordered button varian

---

src/forms/DateTimePicker.jsx
src/forms/TimeInput.jsx
src/forms/__snapshots__/timeInput.test.jsx.snap
src/forms/redux-form/TimeInput.jsx
src/forms/redux-form/__snapshots__/timeInput.test.jsx.snap
src/forms/redux-form/timeInput.test.jsx
src/forms/timeInput.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-82
Time input currently manages its own state and updates it to work with DateTimePicker, but this adds complexity to the component and makes it difficult to work with redux form.
In prep for working with redux form, we should create a redux form wrapper and remove state inside time input and opt for its value coming from props.

Wc 82 time input redux

---

src/forms/TextInput.jsx
src/forms/textInput.story.jsx

Fixes https://meetup.atlassian.net/browse/WC-86
TextInput stories that have a value are non-interactive (you cant type in the field). defaultValue should be passed when possible. 
The exception is the charcounter story, that needs a value (usually given by parent) to display the `value.length`. I put a note in the infowrapper as to why this is non-interactive.

Wc 86 textinput storybook fix

---

src/layout/GridList.jsx
src/layout/gridList.story.jsx
src/layout/gridList.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-418
Needed for https://meetup.atlassian.net/browse/MW-1845
Added a prop for passing custom class names to GridList items

Added the option to pass custom class names to gridlist items

---

assets/scss/components/_all.scss
assets/scss/components/_calendar.scss

Fixes https://meetup.atlassian.net/browse/WC-89
accidentally threw out the flatpickr partial in the scss of datetime picker.
readding a partial for calendar.

Wc 89 readd flatpickr scss import

---

src/interactive/toast.story.jsx

Wasn't passing a Toast with the `autodismiss` prop set to `false` in the "don't automatically dismiss" story

Fixed story for non-dismissable toast

---

assets/scss/components/_button.scss
src/forms/Button.jsx
src/forms/button.story.jsx

Fixes https://meetup.atlassian.net/browse/SDS-406
Button updates from design team - `<Button bordered>` always gets a shadow on hover, any other button can have a shadow on hover using the `hasHoverShadow` prop, `[disabled]` buttons never get hover shadows.

Button hover shadows

---

assets/scss/components/_modal.scss
src/interactive/Modal.jsx
src/interactive/modal.story.jsx
src/interactive/modal.test.js

Fixes https://meetup.atlassian.net/browse/WC-74
- since i couldn't think of a reliable way of having modals fixed position yet scrollable I added this as an optional modal for when you need to be able to pull a modal out of the "flow" of the page to be fixed. Good example of this is cancel an event which is a modal inside of a `.card` which has a relative position on it this is causes modals to display inside of the card 😢

WC-74: Adding fixed position option for modals

---

assets/scss/components/_popover.scss
src/interactive/Popover.jsx
src/interactive/popover.test.jsx

Fixes https://meetup.atlassian.net/browse/MW-1692
Clicking out of popover menu was not working in Safari mobile because of an issue with Safari mobile where `click` events are not fired on typically non-interactive elements. Reference: https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile

fix for safari on ios

---

src/layout/Flex.jsx

https://meetup.atlassian.net/browse/MW-1845
`flexStart` wasn't being recognized as a valid value for the `justify` prop, causing React to complain. I discovered this while building the footer

Added flexStart as a valid value for the justify prop

---

src/media/AvatarMember.jsx
src/media/avatarmember.test.js

Fixes https://meetup.atlassian.net/browse/SDS-424
This PR updates the `AvatarMember` component to support thumbnails on small sizes in order to optimize for the smaller sized images.

AvatarMember - Support thumbnails on small avatars

---

assets/scss/components/_flex.scss
package.json
yarn.lock

Fixes https://meetup.atlassian.net/browse/MW-1983
Corrects flexbox layout issues being seen in browsers like IE11 which still use follow some of the rules from an older flexbox spec

Fix <Flex> layout issues for older browsers

---

src/interactive/Dropdown.jsx

Fixes https://meetup.atlassian.net/browse/WC-105
I may have been the first to notice this because I have this component within a `form` element.

WC-105: Remove duplicate onClick in bindAll; Add preventDefault to onClick handler

---

Makefile
src/forms/redux-form/TextInput.jsx
src/forms/redux-form/__snapshots__/textInput.test.jsx.snap
src/forms/redux-form/textInput.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-430
For field-level validations, redux-form automatically validates on first render unless you check for validation on whether the field has been touched.
It seems as though this is intended behavior.
https://github.com/erikras/redux-form/issues/120
>This is the purpose of the touched flags. In most UI cases, you should only show an error if a field has been touched (gone to and then blurred). There is also a visited flag, which is set to true onFocus. There's a working example of how the flags work here.
>Does that help?
Docs for `meta.touched`: https://redux-form.com/7.0.4/docs/api/field.md/#-code-meta-touched-boolean-code-
This ticket is to adjust the current `ReduxFormTextInput` implementation to take a flag that, when passed in, does not …

SDS-430: add validateBeforeTouched option to ReduxFormTextInput

---

src/forms/redux-form/TogglePill.jsx
src/forms/redux-form/__snapshots__/togglePill.test.jsx.snap
src/forms/redux-form/togglePill.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-106
The problem: Redux Form's implementation for checkboxes sets the value as `true` or `false`, unlike expected html behavior that separates `name`, `value`, and `checked`. 
https://github.com/erikras/redux-form/issues/2922
If we want our TogglePill's to be `checked`, we need to read the `input.value` prop from Redux Form (which is true or false), and pass that to `isActive`.

Wc 106 redux form toggle

---

src/forms/SelectInput.jsx
src/forms/redux-form/SelectInput.jsx
src/forms/redux-form/selectInput.test.jsx
src/forms/selectInput.story.jsx
src/forms/selectInput.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-435
We love standardization. Also, we need this for ReduxForm.

SDS-435: Update selectinput to use `error` 

---

src/forms/redux-form/TogglePill.jsx
src/forms/redux-form/togglePill.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-107
the toggle pill should check that the `value === true` not `'true'` in order to set `isActive`. I assumed the value was going to be stringified, but it turns out its a bool.
*AFAIK no other code is using ReduxTogglePill yet except for my branch in PR, so I dont think this is a  breaking change*

ReduXFormTogglePill should check true as bool

---

assets/scss/components/_accordion.scss
src/interactive/AccordionPanel.jsx
src/interactive/AccordionPanelGroup.jsx
src/interactive/accordion.story.jsx
src/interactive/accordion.test.jsx
src/utils/WithToggleControl.jsx

re: Prelim label - Will remove once `<ToggleSwitch>` is merged and can be used here
Fixes https://meetup.atlassian.net/browse/WC-102
Adds the ability to open and close panels with a toggle control instead of simply showing an icon
Will add when I replace `<TogglePill>` with the new `<ToggleSwitch>`

Accordion - added the ability to have a toggle control instead of icon

---

assets/scss/components/_popover.scss

Popover menu options will always be colored `$C_textPrimary` by default

Popover `.inverted` bug fix

---

assets/scss/components/_forms.scss
package.json
src/forms/TextInput.jsx
src/forms/textInput.story.jsx
src/forms/textInput.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-432
Adds the option to have text inputs with icons. Chose to use a `background-image` instead of `<Icon>` in order to have the least changes to `<TextInput>` as possible.

TextInput with icon

---

src/forms/CalendarComponent.jsx
src/forms/calendarComponent.story.jsx
src/forms/calendarComponent.test.jsx
src/forms/redux-form/__snapshots__/calendarComponent.test.jsx.snap

Relates to https://meetup.atlassian.net/browse/MUP-15668
Updating values via the `datepickerOptions` prop does not actually update the flatpickr config in `CalendarComponent`. This currently only gets set on `componentDidMount`. This causes a problem when trying to set a date range based off of the value of another date picker, for example. This PR fixes that and allows you to dynamically set the config of the flatpicker by passing an updated `datepickerOptions` prop.
`Prettier` seems to have made the diff larger than necessary - sorry about that.

CalendarComponent datepickerOptions prop updates

---

src/forms/Checkbox.jsx
src/forms/checkbox.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-110
the `onChange` call should be passed the `e` `event` arg,  rather than the value.
Not sure if something was dependent on the checked value in particular, but passing `e` will allow it to work with `onChange` coming from `redux-form`.
*Some background:*
the call to `props.onChange` was added so that delete events would be supported here:
https://github.com/meetup/mup-web/blob/5b7940b87e0142276df3eb031c3f1629d233d1c3/src/app/group/event/home/ConfirmCancelModal.jsx#L160
but the handler doesn't do anything with the args, so it shouldn't be a problem to change the signature.
https://github.com/meetup/mup-web/blob/5b7940b87e0142276df3eb031c3f1629d233d1c3/src/app/group/event/home/ConfirmCancelModal.jsx#L98
the `onChange` is also supplied here …

Wc 110 checkbox onchange event

---

src/interactive/Toaster.jsx

Toasts with `autodismiss` prop set to `false` would still dismiss toasts if the toast was hovered

Non-dismissing toast hover bugfix

---

Makefile
assets/scss/components/_button.scss
assets/scss/util/_color-mappings.scss
package.json
src/forms/Button.jsx
src/forms/button.story.jsx
yarn.lock

These changes aren't "breaking", but there are a few buttons we want to change to the "neutral" style. **How should this be versioned?**
Fixes https://meetup.atlassian.net/browse/SDS-426
Updated default button background color to be `$C_blue`, added a new quieter button style called "neutral"
New default button style:
New variant of button called "neutral" (formerly default button style):

Update button styles

---

src/interactive/Popover.jsx

Fixes https://meetup.atlassian.net/browse/WC-117
Need to add `e.preventDefault` so that when a `<Popover />` resides within a `<form>`, it doesn't cause the form to be submitted.

preventDefault in Popover onClick handler

---

src/forms/TimeInput.jsx
src/forms/timeInput.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-119
props.onChange (which is usually set by reduc form) currently sends over e.target.value. redux form expects the event.

send whole event in props.onChange

---

assets/scss/components/_popover.scss

Using a more specific selector to color menu item text

Ensure popover menu item always has dark text color

---

src/interactive/AccordionPanelGroup.jsx

Fixes https://meetup.atlassian.net/browse/WC-121
Props on accordion panels in accordion panel group become stale, since we are cloning the `this.accordionPanels` which get set on init, rather than whats coming in updated from props.
As a result the panels and panel content weren't getting fresh props and not updating.
relates a bit to https://github.com/meetup/meetup-web-components/pull/330/

Clone accordionPanels to get fresh props

---

assets/scss/components/_avatar.scss
assets/scss/components/_button.scss
assets/scss/components/_tabs.scss
assets/scss/util/_color-mappings.scss

We're now using `$C_blue` as an accent color instead of `$C_red` everywhere all of the time.
The only thing that visually changes in this PR is the tab highlight color:

Change red accent colors to blue

---

assets/scss/components/_togglePill.scss
src/forms/RadioButtonGroup.jsx
src/forms/TogglePill.jsx
src/forms/__snapshots__/radioButtonGroup.test.jsx.snap
src/forms/__snapshots__/togglePill.test.jsx.snap
src/forms/radioButtonGroup.story.jsx
src/forms/radioButtonGroup.test.jsx
src/forms/togglePill.test.jsx
src/forms/togglepill.story.jsx

Fixes https://meetup.atlassian.net/browse/WC-124
Toggle pills in radio button group do not fill width when you tell the group to switch to coulmn at smaller widths. 
Right now:
we want it to be like this:

Toggle Pills in radioButtonGroups should be responsive and felx to full width

---

src/forms/CalendarComponent.jsx
src/forms/DateTimeLocalInput.jsx
src/forms/TimeInput.jsx
src/forms/__snapshots__/calendarComponent.test.jsx.snap
src/forms/__snapshots__/dateTimeLocalInput.test.jsx.snap
src/forms/__snapshots__/timeInput.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/MW-2475
Date, time, and datetime inputs were getting default `<select>` styling in mobile browsers. This PR fixes that, but I'm stumped on how we can safely show the down chevron when the input behaves as a `<select>`.

Reset form styles for date and time inputs

---

assets/scss/components/_forms.scss
src/forms/SelectInput.jsx
src/forms/__snapshots__/selectInput.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/WC-127
Added some right padding to <SelectInput> to accommodate the custom arrow

SelectInput arrow overlapping text bugfix

---

src/forms/TextInput.jsx
src/forms/Textarea.jsx
src/forms/__snapshots__/textInput.test.jsx.snap
src/forms/textInput.story.jsx

Moved error element outside of `.inputContainer` so when it get's absolutely positioned, it's always inside the input box
BAD (before):
GOOD (after):

Bugfix - character count layout

---

assets/scss/components/_hscroll.scss
assets/scss/storybook.scss

Fixes https://meetup.atlassian.net/browse/SDS-449
IE doesn't allow horizontal scrolling without using the scroll bars. Instead of brute-force hiding scroll bars all of the time, I'm styling them invisible for browsers that allow that, and doing my best to only show them when necessary for browsers that don't

Enable scroll bars so IE users can horizontally scroll

---

src/forms/Textarea.jsx
src/forms/textarea.test.jsx

Fixes https://meetup.atlassian.net/browse/MW-2692
`autosize.update()` was being called in `componentWillRecieveProps`, so it was calculating height with the previous value, not the current/replaced value

Better autosize height updating for Textarea

---

src/interactive/Dropdown.jsx

Check for new props so we can open/close a Dropdown by changing the value of the `isActive` prop

Allow Dropdown to be toggled via props

---

src/forms/TimeInput.jsx
src/forms/timeInput.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-141
Only allow numbers in the fauxInputs!

WC-141 TimeInput: Disallow characters besides 0 through 9

---

package.json
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-144
It looks like our storybook addon packages got out of date with some of the other dependencies in this project. These package upgrades resolve the `Accessing nonexistent addons channel` errors thrown on certain stories.

update addon packages to fix 'channel not found' addon errors

---

src/interactive/Dropdown.jsx
src/interactive/dropdown.story.jsx
src/interactive/dropdown.test.jsx

Sometimes we want to manually toggle a `<Dropdown>` open and closed. For example: Will needs to close a `<Dropdown>` after a form in the dropdown content is submitted.

Manually toggled dropdown

---

assets/scss/components/_icon.scss
src/media/Icon.jsx
src/media/icon.story.jsx
src/media/icon.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-113
Adds `circled` prop to enable placing a scaled down icon inside a circle of a given media `size`.

support `circled` boolean prop to surround scaled icon in a circle

---

src/forms/TextInput.jsx
src/forms/Textarea.jsx
src/forms/__snapshots__/textInput.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/WC-146
Fields with character counters currently allow screen readers to tab to the characters remaining element, which reads a number out of context.
To fix this and provide better hints, tab navigation to the character counter has been disabled, and the `maxlength` attribute will be used on text areas or text inputs in which the `maxLength` prop is passed. This attribute will alert screen readers to "invalid data" when the max length is exceeded. Depending on the screen reader, the `maxlength` value may also be read to provide a hint.

Wc 146/char counter a11y

---

src/forms/NumberInput.jsx

Fixes https://meetup.atlassian.net/browse/WC-150
Because translation is not supported in shared inputs, there's no easy way to add labels to the increment/decrement buttons in `NumberInput`.
Because we're unable to label the buttons to provide context to screen readers, I've disabled keyboard navigation to these buttons. Keyboard and screen reader users are still able to modify the value by typing or using arrow keys as they would any other native number input.

disallow tab navigation into number input buttons

---

assets/scss/components/_dropdown.scss
src/interactive/Dropdown.jsx
src/interactive/dropdown.story.jsx

Helps with https://meetup.atlassian.net/browse/MW-2973
Yanyi got [a design](https://meetup.atlassian.net/secure/attachment/39667/Event%20%28Upcoming%29.png) that calls for a center-aligned dropdown, so I added `center` as one of the possible directions that can be passed to `align`

Add center-aligned dropdown option

---

assets/scss/components/_button.scss

The design team noticed that the neutral button looks disabled with `$C_textSecondary`, so I've updated the color to be `$C_textPrimary`. There may be more updates to this button style next month

Darken neutral button text color

---

assets/scss/components/_avatar.scss
assets/scss/components/_forms.scss
jest.config.json
package.json
src/forms/TextInput.jsx
src/forms/__snapshots__/textInput.test.jsx.snap
src/forms/textInput.story.jsx
src/media/AvatarMember.jsx
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-145
Fixes no photo avatar and icon text inputs in `mup-web`.
Removes base64 inline loader; refactors `Icon` and `TextInput` components to use actual `Icon` component instead of inline loading a base64 background image.
Shared components should not rely on inline webpack loaders, as it makes them less portable across applications.

Wc 145/rm inline base64 loader

---

assets/scss/components/_dropdown.scss
package.json
src/interactive/Dropdown.jsx
src/interactive/__snapshots__/dropdown.test.jsx.snap
src/interactive/dropdown.story.jsx
src/interactive/dropdown.test.jsx
yarn.lock

Re Prelim:
- ~Still needs tests to be updated~
- ~Need to test in mup-web~
Fixes https://meetup.atlassian.net/browse/WC-152
Dropdown content needs to be rendered in the document body to avoid issues with `z-index` and `overflow`

Render dropdown content in document body

---

assets/scss/components/_dropdown.scss
src/interactive/Dropdown.jsx

Right-aligned dropdowns had two issues:
* calculating `dropdown-content` position based on `this.props.maxWidth`
* `dropdown-content` was being stretched because `left` was being set, and `right` was always 0

Better right alignment for dropdowns

---

assets/scss/components/_avatar.scss

Fixes issue where no photo avatar is displaying `flex` instead of `inline-flex`

use inline-flex instead of flex in no photo avatar

---

src/forms/TextInput.jsx
src/forms/__snapshots__/textInput.test.jsx.snap

The `maxLength` DOM attribute was added to `TextInput` to aid accessibility. We do however, want to allow users to type beyond the max characters for a field in `mup-web`. This branch removes the property in order to revert text inputs to previous behavior.

rm maxLength dom attribute from textInput

---

src/forms/TextInput.jsx
src/forms/Textarea.jsx

Fixes https://meetup.atlassian.net/browse/WC-158
- `TextInput` `value` prop should only be added to the `input` element if the prop is defined. This works around the wonky IE11 event model.
- `Textarea` should **not** have a `maxLength` prop that defaults to `-1`. IE11 will treat a value of `-1` as `0` for the `maxlength` attribute on a text area, which prevents users from interacting with the input. As a workaround, this branch conditionally sets the `maxLength` prop rather than falling back to `-1` as a default.

Wc 158/ie11 text inputs

---

assets/scss/components/_forms.scss
src/forms/Checkbox.jsx
src/forms/__snapshots__/checkbox.test.jsx.snap

Just a small/easy bug Gavin pointed out to me. Not sure when this broke
Before:
After:

Bugfix - vertically align check icon in checkbox

---

.editorconfig

Brings this repo up to date with `mup-web` editor settings

update editorconfig with max line length matching `mup-web` settings

---

src/forms/textInput.story.jsx

Fixes https://meetup.atlassian.net/browse/WC-161
Clarifies documentation for `TextInput` to demonstrate passing a `type` prop for a different input type (e.g. `tel`)

demonstrate type override in textInput story

---

src/utils/components/withMatchMedia.jsx

https://meetup.atlassian.net/browse/MW-2907
Related to / supports this PR https://github.com/meetup/meetup-web-platform/pull/423/files
If initialMedia prop is present, set that in the constructor

withMatchMedia: use initialMedia prop if provided in constructor

---

src/utils/components/withMatchMedia.jsx

Do not pass initialMedia as a prop to the wrapped element. Causes errors in the browser dev console.

remove initialMedia prop from dom elements

---

assets/scss/components/_gridList.scss

When we updated to custom properties, left margin was accidentally set to a positive value instead of a negative

Negative left margin on autoheight gridlist

---

src/forms/TextInput.jsx

This issue came up with Mike A trying to clear a form input in `mup-web`. Passing an empty string to `value` prevents it from getting passed through because it `value` will return false

Allow TextInput value prop pass even if empty string

---

src/forms/TimeInput.jsx

Fixes https://meetup.atlassian.net/browse/WC-169
In a time input component, the time is first set as an empty string. We only care about the valid time, so return out.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Validation
Links back to https://github.com/meetup/mup-web/pull/2540

WC-169: swallow input if value takes in an empty string

---

assets/scss/components/_avatar.scss
package.json
src/media/AvatarMember.jsx
src/media/avatarmember.story.jsx
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-162
- removed unused CSS for `avatar--icon`
- removed base64 uri from avatar styles (replaces org badge img with badge svg icon)
- refactored `avatarCharm` placeholder into a mixin that positions an actual `Icon` component
- updated stories for `AvatarMember` to show available sizes

remove inline base64 img uri from avatar styles

---

.gitignore
assets/scss/components/_accordion.scss
src/interactive/AccordionPanel.jsx
src/interactive/__snapshots__/accordionPanel.test.jsx.snap
src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap
src/interactive/accordionPanel.test.jsx
src/interactive/accordionPanelGroup.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-179
Enables `AccordionPanel` content area to expand to accommodate content of any height when open (as opposed to setting a hard height based on initial content height).

Wc 179/accordion height tollerance

---

src/interactive/AccordionPanel.jsx

Follows up on: https://meetup.atlassian.net/browse/WC-179
Allows `AccordionPanel` content to expand in height beyond the `min-height` originally set in `render()`.

remove 0 height for open accordion panels

---

assets/scss/components/_all.scss
assets/scss/components/_navbar.scss
src/navigation/NavBar.jsx
src/navigation/NavItem.jsx
src/navigation/NavItems.test.jsx
src/navigation/__snapshots__/NavItems.test.jsx.snap
src/navigation/navbar.story.jsx

Fixes https://meetup.atlassian.net/browse/MP-351
Since we want to unify the navigation bar across all of web, create the navigation bar in Meetup-Web Components for easy implementations in any web repo.
Part 1: Create a component to create Navigation Items
DoD:
* Create component and story displaying use
* Nav Item can fulfill pro-web and mup-web's current design
I just copied over mup-web's navItem's component, tests, and styling into meetup-web-components: 
* NavItems: 
https://github.com/meetup/mup-web/blob/master/src/components/chrome/header/HeaderNavItem.jsx
* NavItem Tests:
https://github.com/meetup/mup-web/blob/master/src/components/chrome/header/headerNavItem.test.jsx
* SCSS for NavItems: 
https://github.com/meetup/mup-web/blob/master/src/assets/scss/shared/chrome/_header.scss
The …

Nav Items (MP-351)

---

src/forms/TogglePill.jsx
src/forms/ToggleSwitch.jsx
src/forms/__snapshots__/togglePill.test.jsx.snap
src/interactive/__snapshots__/accordionPanel.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/MG-313
Before this, tab focus was moving from the `<button>` provided by `withToggleControl` into a nested `<input>` instead of moving to the next element

Fix tabbing on components using withToggleControl

---

src/forms/Button.jsx
src/interactive/__snapshots__/accordionPanel.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/WC-192
Render a disabled class when disabled prop is passed to <Button>

Add disabled classname to <Button>

---

src/interactive/AccordionPanel.jsx
src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap

Re Prelim - thinking on whether this is the best solution
Fixes https://meetup.atlassian.net/browse/WC-193
Open `<AccordionPanel>`s collapse their height when AccordionPanelGroup is `multiselectable`. Moved setState stuff from `this._handleToggle` to `componentWillReceiveProps`

Fix non-multiselectable AccordionPanel bug

---

package.json
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-194
Prevent CalendarComponent year from changing on scroll by upgrading `react-flatpickr`. Reported by Gavin and Jackie

CalendarComponent year scrolling

---

assets/scss/components/_calendar.scss

Fixes https://meetup.atlassian.net/browse/SDS-457
Make sure month and year are visible in the calendar dropdown in IE11
Before:
After:

CalendarComponent layout fix

---

assets/scss/components/_card.scss

Fixes https://meetup.atlassian.net/browse/SDS-549
IE11 doesn't understand `min-height: initial`, so I changed it to `min-height: auto`.

Fix <Card initialHeight> in IE11

---

src/forms/TextInput.jsx
src/forms/__snapshots__/textInput.test.jsx.snap
src/forms/textInput.story.jsx

Fixes https://meetup.atlassian.net/browse/SDS-548
Allow engineers to customize the text in the browser's native validation error message
Before (screenshot taken in IE11):
After (screenshot taken in Chrome):

Allow for setting custom validation error message on TextInput

---

src/media/Avatar.jsx

Fixes https://meetup.atlassian.net/browse/SDS-554
Profile icon was showing very small
Before:
After:

<AvatarMember noPhoto> icon not showing in Safari

---

assets/scss/components/_avatar.scss

Fixes https://meetup.atlassian.net/browse/SDS-553
IE11 doesn't like the `initial` value, so I set `text-indent` to 0

AvatarMember icons not showing in IE11

---

assets/scss/components/_gridList.scss
src/layout/GridList.jsx

Fixes https://meetup.atlassian.net/browse/SDS-552
Added a wrapper div to work around IE11 flexbox bug where `box-sizing: border-box;` is ignored for flex items with a `flex-basis`. This was breaking `<GridList autoHeightWithWrap />` - it caused a items to wrap to soon (e.g.: a 3-col grid would only have 2 cols)

<GridList autoHeightWithWrap /> IE11 bug

---

src/forms/TextInput.jsx
src/forms/Textarea.jsx

Fixes https://meetup.atlassian.net/browse/WC-196
Enables soft character limit for char counter fields by avoiding passing the `maxLength` prop as an HTML attribute, which triggers most browsers to give the field a hard limit.

enable soft limit for char counter fields

---

src/forms/CalendarComponent.jsx
src/forms/NumberInput.jsx
src/forms/SelectInput.jsx
src/forms/TextInput.jsx
src/forms/Textarea.jsx
src/forms/TimeInput.jsx
src/forms/__snapshots__/textInput.test.jsx.snap
src/forms/__snapshots__/timeInput.test.jsx.snap

Avoids breaking change with `requiredText` by falling back on "*" as a default required message.

fall back to '*' for required field requiredText

---

src/forms/Button.jsx
src/forms/NumberInput.jsx
src/interactive/__snapshots__/accordionPanel.test.jsx.snap

`<button type="button">` prevents buttons from being activated in a form when you hit "enter" within an `input` to submit the form

Default "type" prop for `Button`

---

src/forms/redux-form/Textarea.jsx
src/forms/redux-form/__snapshots__/textarea.test.jsx.snap

Fixes an issue on the schedule form where some textareas were showing validation error states before touched.

pass error in textarea redux form wrapper only when field has been touched.

---

assets/scss/components/_accordion.scss
src/interactive/AccordionPanel.jsx
src/interactive/AccordionPanelGroup.jsx
src/interactive/__snapshots__/accordionPanel.test.jsx.snap
src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap
src/utils/components/WithToggleControl.jsx

Re Prelim tag:
Fixes https://meetup.atlassian.net/browse/SDS-230
A less severe focus state for `AccordionPanel` that only shows for users navigating with a keyboard
Interacting using a keyboard:
Interacting using a cursor:

Visual improvements to :focus for AccordionPanel

---

assets/scss/components/_button.scss
src/forms/Button.jsx
src/forms/button.story.jsx

Fixes https://meetup.atlassian.net/browse/SDS-542
Most of our designs override the left and right padding on buttons that _only_ contain an icon
Before:
After:

Icon-only button padding

---

src/forms/Typeahead.jsx

Fixes https://meetup.atlassian.net/browse/MG-710
- Typeahead component was staying open when no results were found. It should not display the results box unless results are found.
BEFORE:
AFTER:

only show opened results if there are any results

---

assets/scss/components/_dropdown.scss
src/interactive/Dropdown.jsx
src/interactive/dropdown.story.jsx
src/interactive/dropdown.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-568
The padding on `dropdownMenu-item` was causing it's children not to be clickable unless you clicked directly on the child element. It's even harder to click on the child element when it's an inline element.

Make entire dropdown menu item area clickable

---

src/forms/NumberInput.jsx
src/forms/Typeahead.jsx

Fixes https://meetup.atlassian.net/browse/MG-805
The NumberInput component only set the `value` from props in state in the constructor once, but sometimes redux form will update the initial values on the form after the field has mounted

if we recieve a new value prop, update the input

---

src/forms/TimeInput.jsx

Fixes https://meetup.atlassian.net/browse/WC-209
Firefox has no good way of hiding the native clear button in `input[type="time"]`, so I decided to just keep it around and make it clear the input.
However, Malik made a change to `return` if the input value was empty on change. Instead of throwing out the change entirely, I set it to `00:00`.

Make the browser-native clear button work on TimeInput

---

src/Footer.jsx
src/__snapshots__/footer.test.jsx.snap
src/footer.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-215
Noticing that the social icons in the site footer don't link to language-specific social sites anymore.
Steps to reproduce:
1. log out
2. go to the footer on meetup.com
3. pick french language
4. click on Twitter icon
It should go to https://twitter.com/MeetupFR/ but is instead going to https://twitter.com/Meetup/. Some other languages also have their own language-specific fb and twitter pages.

Pass localeCode to getSocialLinks and update snaps

---

package.json
src/forms/Typeahead.jsx
src/forms/typeahead.test.jsx
yarn.lock

Fixes https://meetup.atlassian.net/browse/WC-208
For some reason, the Typeahead isn't reliably changing it's internal state when a user hovers a new item in the dropdown. I think this might be an issue with [Downshift](https://github.com/paypal/downshift), but I can't identify what it is in order to submit a PR to them.
This is a bit "brute force", but I'd love to hear

Manually update Typeahead's highlighted index

---

src/layout/FormSection.jsx
src/layout/__snapshots__/formSection.test.jsx.snap
src/layout/formSection.story.jsx
src/layout/formSection.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-97
Making `<FormSection />` available to all Meetup web apps.
After this is merged, we'll need to follow up to remove `FormSection` code from `mup-web` and replace usage with this

Port FormSection from mup-web

---

Makefile
README.md
src/forms/redux-form/CalendarComponent.jsx
src/forms/redux-form/NumberInput.jsx
src/forms/redux-form/SelectInput.jsx
src/forms/redux-form/TextInput.jsx
src/forms/redux-form/Textarea.jsx
src/forms/redux-form/TimeInput.jsx
src/forms/redux-form/__snapshots__/calendarComponent.test.jsx.snap
src/forms/redux-form/__snapshots__/numberInput.test.jsx.snap
src/forms/redux-form/__snapshots__/timeInput.test.jsx.snap
src/forms/redux-form/numberInput.test.jsx
src/forms/redux-form/selectInput.test.jsx
src/forms/redux-form/textInput.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-204
For all `redux-form` wrappers that handle errors, check `meta.touched`. This ensures validation on the field will not show an error until a user has interacted with it unless the `validateBeforeTouched` prop is passed.

use meta.touched in all redux-form wrappers that handle errors

---

assets/scss/components/_dropdown.scss
src/interactive/dropdown.story.jsx

Fixes https://meetup.atlassian.net/browse/WC-214
Instead of always wrapping on word breaks or using `white-space: nowrap` to make sure text in Dropdown menuItems doesn't ever wrap, have the text wrap only when the text has made use of all available space decided by `max-width`
Before (wrapping too soon):
After:

Better handling of text wrapping on Dropdown menuItems

---

assets/scss/components/_footer.scss
src/Footer.jsx
src/__snapshots__/footer.test.jsx.snap
src/footer.story.jsx
src/footer.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-216
Adds a `legalCopy` prop to the `Footer` comp for GDPR compliance.
See ticket, but here is the idea...

Footer: adding legalCopy prop for GDPR

---

assets/scss/components/_togglePill.scss
src/forms/TogglePill.jsx
src/forms/__snapshots__/togglePill.test.jsx.snap
src/forms/radioButtonGroup.story.jsx
src/forms/redux-form/__snapshots__/togglePill.test.jsx.snap
src/utils/components/ToggleWrapper.jsx
src/utils/components/WithToggleControl.jsx
src/utils/components/__snapshots__/toggleWrapper.test.jsx.snap
src/utils/components/toggleWrapper.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-191
Radio-style `TogglePill`s are now keyboard navigable. I built a wrapper component as a part of this fix, and I created a [follow-up ticket](https://meetup.atlassian.net/browse/SDS-589) to replace `withToggleControl` usage

TogglePill radio keyboard nav

---

src/interactive/AccordionPanel.jsx
src/interactive/__snapshots__/accordionPanel.test.jsx.snap
src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap
src/interactive/accordion.story.jsx
src/interactive/accordionPanel.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-588
Focus styles are visible again, and panels can be toggled using the keyboard. Also did a little cleanup, especially in tests.

Fix Accordion keyboard navigation

---

package.json
src/forms/Typeahead.jsx
src/forms/typeahead.story.jsx
src/forms/typeahead.test.jsx
yarn.lock

Fixes https://meetup.atlassian.net/browse/MG-1159
This bug is hard to reproduce, but sometimes clicking a Typeahead item would not update the selected item. I've had luck reproducing in Safari with lots of reloading.
These changes may bring back an issue where hovering a TypeaheadItem that was added after mount doesn't get a visual hover state, but I was unable to reproduce using `setTimeout` to add new items.
https://giphy.com/gifs/mobile-test-case-orTE5JSA9j0rh5JLCu

Address Typeahead selection issues when clicking an item

---

assets/scss/components/_navbar.scss
src/navigation/Nav.jsx
src/navigation/__snapshots__/Nav.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/MP-947
Clickable area of the meetup logo stretches all the way through the whitespace, this PR fixes that problem.

fixing logo stretch problem in navbar

---

src/forms/TypeaheadItem.jsx
src/forms/typeahead.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-224
Updated PropType for `TypeaheadItem`'s value prop
Tested with an object and got no warnings:

Fix TypeaheadItem PropType warning

---

src/forms/Typeahead.jsx
src/forms/typeahead.story.jsx
src/forms/typeahead.test.jsx

Fixes https://meetup.atlassian.net/browse/SDS-595
Passed a default `itemsToString` function to handle warnings from Downshift for TypeaheadItem values that are not strings.

Get rid of `itemsToString` warnings

---

src/interactive/Dropdown.jsx
src/interactive/Tooltip.jsx
src/interactive/dropdown.story.jsx
src/interactive/tooltip.story.jsx
src/utils/components/FloatingPosition.jsx
src/utils/components/floatingPosition.test.jsx

Re Prelim label:
~Still need to add tests~
Fixes https://meetup.atlassian.net/browse/WC-225
Added functionality to `FloatingPosition` to reposition popup content if it overflows the viewport

Ensure Dropdowns and Tooltips are not clipped by the viewport

---

assets/scss/components/_typeahead.scss
src/forms/Typeahead.jsx
src/forms/typeahead.story.jsx

Fixes https://meetup.atlassian.net/browse/WC-227
Added a prop to Typeahead that lets the menu open in document flow instead of appearing above things

Typeahead with menu that opens in document-flow

---

src/interactive/Modal.jsx

Fixes https://meetup.atlassian.net/browse/SDS-637
We introduced a bug with `focus-trap` where clicks were not being handled on elements outside the `FocusTrap` component

Dismiss Modal when clicking overlay shim

---

src/forms/CalendarComponent.jsx
src/forms/calendarComponent.test.jsx

The Flatpickr onChange callback is called with some additional args that are currently being swallowed - this PR makes sure they are available to any passed-in `onChange`
This is non-breaking for all current uses of CalendarComponent that only care about the first arg

pass along date string and instance

---

src/layout/GridList.jsx
src/layout/InlineBlockList.jsx

Fixes https://meetup.atlassian.net/browse/WC-232
Return list layout components unwrapped by default - only wrap them when `isLoading` is true

Return unwrapped InlineBlockList by default

---

src/navigation/Nav.jsx

Fixes https://meetup.atlassian.net/browse/MP-1203
SSR does not support withmatchMedia HOC, so first render of navbar has the wrong size state rendered.
This fix is to provide parent media object from connectWithMatchMedia which is supported on the server side.
There is a link to a thread on slack around that problem
https://meetuphq.slack.com/archives/C2GLWSMAA/p1527075866000363

navbar flickering on pro pages fix

---

src/navigation/Nav.jsx

Relates to https://meetup.atlassian.net/browse/MP-1203
Fixes https://meetup.atlassian.net/browse/MP-1226
SSR does not support withmatchMedia HOC, so first render of navbar has the wrong size state rendered.
The initial fix was to provide parent media object from connectWithMatchMedia which is supported on the server side. There is a link to a thread on slack around that problem:
https://meetuphq.slack.com/archives/C2GLWSMAA/p1527075866000363
However there is a more elegant solution for this fix: 
```jsx
import { Nav } from 'meetup-web-components/lib/Nav';
import connectWithMatchMedia from 'mwp-app-render/lib/components/connectWithMatchMedia';
const EnhancedNav = connectWithMatchMedia(Nav);
...
<EnhancedNav ... />
```
This ticket reverts meetup/meetup-web-components#545

Revert "Navbar Flickering on Pro Pages Fix"

---

CHANGELOG.md
Makefile
src/navigation/Nav.jsx
src/navigation/nav.story.jsx

Fixes https://meetup.atlassian.net/browse/MP-1229
SSR does not support withmatchMedia HOC, so first render of navbar has the wrong size state rendered.
The initial fix was to provide parent media object from connectWithMatchMedia which is supported on the server side, but this was reverted. There is a link to a thread on slack around that problem:
https://meetuphq.slack.com/archives/C2GLWSMAA/p1527075866000363
The pro-web solution for this fix:
```jsx
import { Nav } from 'meetup-web-components/lib/Nav';
import connectWithMatchMedia from 'mwp-app-render/lib/components/connectWithMatchMedia';
const EnhancedNav = connectWithMatchMedia(Nav);
...
<EnhancedNav ... />
```
Accept the media passed by connectWithMatchMedia from pro-web in meetup-web-components.

Accept Media (MP-1229)

---

src/interactive/Tabs.jsx

Compare name to 'TabsTab' string instead of TabsTab class

Correct TabsTab child proptype validation

---

CHANGELOG.md
Makefile
assets/scss/components/_modal.scss
src/interactive/Modal.jsx
src/interactive/modal.story.jsx
src/interactive/modal.test.js

Fixes https://meetup.atlassian.net/browse/SDS-672
Added a prop to `Modal` that allows us to make the close area of a modal stick to the top of the modal

Sticky modal close area

---

assets/scss/components/_typeahead.scss

Fixes https://meetup.atlassian.net/browse/SDS-673
Fixes minor spacing issue with Typeaheads
Before:
After:

Fix Typeahead border-radius gap

---

src/forms/Textarea.jsx
src/forms/textarea.test.jsx

Fixes https://meetup.atlassian.net/browse/WC-240
Replaced deprecated methods `componentWillReceiveProps` and `componentWillMount` with static `getDerivedPropsFromState` method. Updated tests as needed, but filed [a follow-up ticket](https://meetup.atlassian.net/browse/WC-248) to get better test coverage

Textarea for React 17

---

.flowconfig
assets/scss/components/_button.scss

Fixes https://meetup.atlassian.net/browse/SDS-696
Made some updates to `:hover`, `:active`, and `:focus` states per the design team

New styles for boredered button hover

---

assets/scss/components/_flex.scss
package.json

Soon we'll be launching a version of `swarm-sasstools` that removes Bourbon. As a result, browser prefixing or usage of mixins imported from Bourbon will not work in an app that has not been upgraded `mwp-cli` to version `8.0` or higher.
Bourbon will be removed as soon as I can clean any traces of it's usage in component styles.

Temporarily add Bourbon as a dependency

---

src/forms/CalendarComponent.jsx
src/forms/calendarComponent.test.jsx

Fixes https://meetup.atlassian.net/browse/MP-1555
Flatpickr might call onChange with non-existent date. Seems like this happens when we provide date constraints (minDate, maxDate) without selecting any date yet.
Like in that case where we have two date fields and they affect each other.
This PR fixes this problem. It does not parse if the date has not been selected yet.

fixing calendar component invalid date parse attempt

---

assets/scss/components/_forms.scss

Fixes https://meetup.atlassian.net/browse/SDS-717
See screenshots
Before:
After:

Firefox - hide browser-native spinner in input[type=number]

---

assets/scss/components/_card.scss

Fixing card styles so that they wrap, when cards are in hscroll components copy doesn't wrap cause hscroll has a white-space: nowrap, this causes a lot of copy in cards to flow outside of the box

card copy isnt wrapping

---

assets/scss/components/_adminBar.scss
src/interactive/AdminBar.jsx
src/interactive/AdminBar.story.jsx
src/interactive/__snapshots__/AdminBar.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/1689
Before (new branch created to match new jira ticket):  https://github.com/meetup/meetup-web-components/pull/588
Group should be an optional param for AdminBar component - pro-web doesn't not need to display the buttons or group related information.
AdminBar on pro-web
using prodApi:
using QL and prodApi:
using QL and !prodAp:
prodApi:

Update admin bar - make group an optional param

---

src/interactive/AdminBar.story.jsx

`addWithInfo` was removed from Storybook in version 4, and is now only available through the [Storybook info addon](https://github.com/storybooks/storybook/tree/master/addons/info)

Remove addWithInfo usage in AdminBar stories

---

src/interactive/AdminBar.jsx
src/interactive/AdminBar.story.jsx
src/interactive/AdminBar.test.jsx
src/interactive/__snapshots__/AdminBar.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/MP-1717
On Pro display warning about using production data if:
prodApi={true}, 
isAdmin={false}, 
nodeEnv={development}
Now we can see the red warning bar even if isAdmin is false.

Display warning when using prodApi=true, isAdmin=false, nodeEnv=development

---

src/forms/NumberInput.jsx

Make the numberInput field width longer because currently if the max is 10 it will cut off if a user types in 100. The expected behavior is that if a user is able to type in 100 that 100 should not be cut off.

increase width of numberInput

---

assets/scss/components/_card.scss

Per design's request, removing 1px border from shadow on the `Card` component
Looks like this now:

reduce card shadow border

---

src/forms/FieldsetTime.jsx
src/forms/fieldsetTime.test.jsx

Fixes https://meetup.atlassian.net/browse/MG-2471
The text-based time input was topping out at 'max - 1' instead of max.
This is really just a one-character code change, but I've fixed some comment typos and added unit tests for the problematic function

fix 'max' comparison and add tests

---

src/media/AvatarMember.jsx
src/media/avatarmember.test.js

https://meetup.atlassian.net/browse/MG-2498
mup-web pr: https://github.com/meetup/mup-web/pull/4139
From new member_list endpoint we receive only `highres_link` and `thumb_link` for Photo. Use `highres_link` as a fallback for large size in case `photo_link` is not present.

Use highres_link in AvatarMember

---

src/interactive/Tooltip.jsx
src/interactive/tooltip.story.jsx

Fixes https://meetup.atlassian.net/browse/MG-2364
Accidentally removed the ability to click on the x in the tooltip to close it. This adds it back and allows the ability to close the tooltip by clicking outside of it.

allow manual toggle of tooltip

---

assets/scss/components/_flex.scss
src/forms/RadioButtonGroup.jsx
src/layout/Flex.jsx
src/layout/flex.story.jsx
src/layout/flex.test.jsx

Fixes https://meetup.atlassian.net/browse/MG-2708
Adds the option to justify flex item padding to the right instead of to the left. Not convinced about the naming.

Adds justifyItems to Flex component

---

src/media/Avatar.jsx
src/media/avatar.story.jsx
src/navigation/__snapshots__/Nav.test.jsx.snap
src/navigation/components/notifications/__snapshots__/Notifications.test.jsx.snap

Fixes https://meetup.atlassian.net/browse/sds-676
This pr adds `aria-label` to `<Avatar />` and sets the value to the `alt` prop. I added a default prop to `<Avatar />` instead of requiring one because I didn't want to introduce a breaking change and am unsure if any teams builds fail on lint errors.

Allow screen readers to read alt text on the Avatar component

---

CHANGELOG.md
Makefile
src/interactive/Dropdown.jsx
src/interactive/dropdown.story.jsx
src/interactive/dropdown.test.jsx

Revert of https://github.com/meetup/meetup-web-components/pull/642
- Sadly after many different iterations and with the help of @browne0 and @hsbacot, we've determined that 
there was no easy way to add a prop that would allow us to close the Dropdown after item menu click _and_ be simpler to use than `manualToggle` in conjunction with `isActive`. 
- Some iterations did indeed work, but added only to the complexity and overhead that we were trying to avoid in the first place. 
- As it stands right now, `manualToggle` seems to be the best way to close the Dropdown after menu item click. This might be worth revisiting in the future.

deprecating

---

assets/scss/components/_modal.scss

Fixes https://meetup.atlassian.net/browse/sds-740
This allows scrolling on containers that aren't the body on ios
More info here: https://github.com/tachyons-css/tachyons/issues/566

adding webkit overflow scroll so that ios scrolls modal content

---

package.json

Fixes https://meetup.atlassian.net/browse/SDS-726
Configured `lint` command to only run eslint on the `src` directory allowing it to ignore the linting errors on the compiled code in `lib/`.

linting only src directory

---

src/utils/components/withMatchMedia.story.jsx

Would like to raise awareness of connectWithMatchMedia, which is superior to withMatchMedia because it sets a default media based on device (detected from user agent) before we can detect the viewport size

add info on connectWithMatchMedia to docs

---

assets/scss/components/_avatar.scss

https://meetup.atlassian.net/browse/MG-3930
This shrinks avatars from 150px at the largest media query to 120px there, and maintains 120px at the smallest.

Shrink largest avatar size from --responsiveMedia-xxl to --space-6

---

assets/scss/components/_forms.scss
package.json
yarn.lock

Updating swarm-sasstools version and making input icons darker to have better contrast
Fixes https://meetup.atlassian.net/browse/SDS-796

Updating input borders and icons to be darker for more contrast

---

assets/scss/components/_navbar.scss
src/navigation/Nav.jsx
src/navigation/components/profile/ProfileDropdown.jsx
src/navigation/nav.story.jsx

Task: https://meetup.atlassian.net/browse/OG-338
This is bug fixing for some of the task OG-338 and the previous PR for this task was: https://github.com/meetup/meetup-web-components/pull/668
Now we have to change the statement for showing the groups listing, because we have to catch the case when we have no groups listed, but we have a draft group.

OG-338: fixing groupDraft position in object

---

src/forms/Select.jsx

Fixes https://meetup.atlassian.net/browse/SDS-874
Updated `Select` component in `meetup-web-components` to use new [`Select`](https://github.com/meetup/swarm-ui/blob/master/packages/swarm-components/src/Select.jsx) component from `swarm-components`.
DoD:
- removed `className`, `labelClassName`, `selectClassName` props
- added flow type and documented optional `id` attribute (was used before)
- updated `required` (`boolean` or `string`) prop handling to match new `requiredText` (`string`) API
- checked Storybook examples to make sure they still function properly
- made some fancy screenshots and used `perceptualdiff` package to compare them (after I caught a bug with `required` prop and fixed it), including one for reference here
Before:
After:
Diff:

SDS-874 Migrated Select to use new Swarm UI components

---

src/forms/TextInput.jsx
src/forms/textInput.story.jsx

Fixes https://meetup.atlassian.net/browse/SDS-875
Updated `TextInput` component in `meetup-web-components` to use new `TextInput` component from `swarm-components`.
DoD:
* removed className, labelClassName, selectClassName props
* added flow type and documented optional id attribute (was used before)
* updated required (boolean or string) prop handling to match new requiredText (string) API
* checked Storybook examples to make sure they still function properly
Outstanding use-cases:
* How do we support these elements? Do we have a helper for this?
* Do we even need this, need final decision
* `pattern` prop is passed through as before but it doesn't seem to affect anything (now or before, is this a bug or we are not testing it properly
* `withErrorList` seems to be styled differently now …

Basic TextInput migrated, still need to replicate a few props.

---

src/forms/__snapshots__/togglePill.test.jsx.snap
src/forms/redux-form/TogglePill.jsx
src/forms/redux-form/__snapshots__/togglePill.test.jsx.snap
src/forms/redux-form/togglePill.test.jsx
src/forms/togglePill.test.jsx

JIRA https://meetup.atlassian.net/browse/SDS-909
Fixes the tests for TogglePill MWC.
**Outstanding question:**
Even though I made tests pass for `redux-forms/TogglePill`, it does throw a few warnings and is effectively broken, at least because it sets `boolean` for `value` prop on MWC `TogglePill` which expects a `string`. It isn't used in `mup-web` or `pro-web` (based on my cursory look) so I suggest we just get rid of `redux-form` version of `TogglePill`.

SDS-909 fix tests for TogglePill

---

src/interactive/Modal.jsx

**Task: ** https://www.pivotaltracker.com/n/projects/2346583/stories/165923751
**Description**
The close button on modals should be a reset button.
Currently the button is a default button so the default styles are applied. The reset prop needs to be applied to strip the styles from the button.
Places this occurs:
+ Update Checklist

165923751: fixing close button styles of modal component

---

src/SignupModal.jsx
src/__snapshots__/SignupModal.test.jsx.snap

Fixes https://www.pivotaltracker.com/story/show/166418085
**Why**
There are numerous ways to navigate to the Member Registration page (secure.meetup.com/register) and these ways have different variations that product, marketing & analysts need to be able to understand.
**As a** GA user
**I want** to see when a member's registration flow starts from the "Sign Up" button in the header or footer on the new guest homepage experience (meetup.com)
**So I can** visualize the flow a user experienced when registering or where they may have fallen off
**What is the desired behavior?**
Acceptance Criteria
Scenario:
Given a guest on (meetup.com [new experience])
When the guest clicks sign up in header or footer)
Then a JS event needs to push data into the dataLayer (see criteria in "More info" below …

add click tracking to sign up modal

---

src/navigation/nav.story.jsx

converts jest references to noops in `.story` files since jest stubs aren't available in storybook -> https://github.com/meetup/meetup-web-components/pull/718/files#diff-d6fadcf8dc8e7c7f0b9d6392d378f7b7R37

jest declarations to noops

---

package.json
yarn.lock

Fixes https://meetup.atlassian.net/browse/OG-1147
Updated the swarm-components version in order to have the latest version. In particular, we wanted the number of chars remaining in textInput to appear which is happening in latest version but not previous version.
Once `meetup-web-components` is updated with the latest `swarm-components` then the version of `meetup-web-components` in`mup-web` will also need to be updated accordingly.

OG-1147 increment swarm-components version to latest

---

src/navigation/Nav.jsx
src/navigation/__snapshots__/Nav.test.jsx.snap
src/navigation/nav.story.jsx

https://www.pivotaltracker.com/story/show/167588973
For several months we've been showing logged-in users a link to Meetup Experiences. This is the first of several PRs that will expose it to logged-out users.  
Mup-web isn't passing `experiences` if you're logged out...yet. So there's nothing to screenshot here.

Display Experiences link to logged-out users in NYC

---

src/navigation/Nav.jsx
src/navigation/__snapshots__/Nav.test.jsx.snap

https://www.pivotaltracker.com/story/show/167588973
Allow unauth items to have icons, too. I have tested this locally to ensure nothing blows up with the unauth links that *don't* have icons.

Add icon on unauth nav items

---

src/forms/Typeahead.jsx
src/utils/components/DeprecationWarning.jsx

Updates typeahead to use `TextInput` from `@meetup/swarm-components`

typeahead to use textinput from swarm

---

src/forms/LockedBadge.jsx
src/forms/__snapshots__/LockedBadge.test.jsx.snap
src/interactive/__snapshots__/accordionPanel.test.jsx.snap

https://app.clubhouse.io/meetup/story/21562/under-manager-group-more-add-api-greyed-our-with-an-upgrade-option
Need to add optional 'preventDefault' flag prop to use link href in parent elements.

[CH-21562] Upgrade locked badge with optional 'preventDefault' flag prop

---

src/navigation/components/dashboard/DashboardDropdown.jsx
src/navigation/components/dashboard/DashboardDropdown.test.jsx
src/navigation/components/dashboard/__snapshots__/DashboardDropdown.test.jsx.snap

Story details: https://app.shortcut.com/meetup/story/64939
Make members in pro dashboard optional.

feat: [sc-64939] [AWS mods] - Removal of the entire Members tab from the Pro Dashboard

---

src/__snapshots__/footer.test.jsx.snap
src/navigation/Nav.jsx

[Shortcut](https://app.shortcut.com/meetup/story/66152/fe-desktop-update-core-nav-bar)
new `mup-web`
to match `pro-web`

Feature/sc 66152/fe desktop update core nav bar

---

src/forms/Checkbox.jsx
src/forms/__snapshots__/checkbox.test.jsx.snap

Story details: https://app.shortcut.com/meetup/story/73275
Moving checkbox from swarm-ui, because [swarm-ui](https://github.com/meetup/swarm-ui) is not deployable and planned to be deprecated.
Added aria-label for accessibility.

feat: [sc-73275] [Pro Dashboard] - custom controls - ARIA toggle fields must have an accessible name

---

src/interactive/Tooltip.jsx
src/interactive/__snapshots__/tooltip.test.jsx.snap

`aria-labelledby` should be added only when element with id exist
role `button` was added only for active status when component have `aria-labelledby` to avoid mistakes

Event Create custom controls Elements must [sc-73276]

---

assets/css/main.css
assets/css/tailwind.min.css
src/interactive/__snapshots__/accordionPanel.test.jsx.snap
src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap
src/media/Icon.jsx

Set the presentation role as the default for our image component.
In many cases, we use an icon with the `img` role without an `aria-label`, which can cause a lot of errors. In my opinion, it would be better to set an `aria-label` for icons that are used without supporting text, instead default role `img`.

Web Alt text Event Create page [sc-72006]

---

assets/css/main.css
assets/scss/components/_button.scss
assets/scss/util/_vars.scss

This PR 
- updates values of `--color-meetup-red` and `--color-viridian` css variables, because it's value defines in non-deployable swarm-ui repo
- updates styling of primary button

Updated `meetup-red` and `viridian` values globally for meetup-web-components 

---

assets/css/main.css
assets/scss/components/_infoToggle.scss

https://app.shortcut.com/meetup/story/73296/pro-dashboard-an-icon-lacks-3-to-1-contrast-ratio
**Description:**
Contrast ratio issue, screenshot from the deque task:
**Fix:** Updating the background color for this icon. Expecting the contrast ratio to go from 1.7 to 3.47.

[SC-73296] An icon lacks 3 to 1 contrast ratio

---

assets/css/main.css
assets/scss/components/_all.scss
assets/scss/components/_textInput.scss
src/forms/SwarmTextInput.jsx
src/forms/TextInput.jsx
src/forms/__snapshots__/textInput.test.jsx.snap
src/forms/textInput.story.jsx

I moved Text input from swarm-ui, to add a curr label and synchronize it by style with the input.
For it just use props `currencyLabel`

FE Add currency label to discounted price [sc-93677]

---

src/forms/Checkbox.jsx
src/forms/__snapshots__/checkbox.test.jsx.snap
src/forms/checkbox.story.jsx

Story details: https://app.shortcut.com/meetup/story/74797
1) Make checkbox `checked` value accessible with keyboard "Enter" key.
2) Fix tabindex error:
Meetup web components storybook:
Pro-web:

feat: [sc-74797] Pro Dashboard: Function cannot be performed by keyboard alone

---

assets/css/main.css
assets/css/tailwind.min.css
src/forms/__snapshots__/select.test.jsx.snap
src/forms/__snapshots__/textInput.test.jsx.snap
src/forms/__snapshots__/textarea.test.jsx.snap
src/utils/a11yPassThrough.js

Bug/sc 98481/bug fe vqa issues on promo code modal

---

assets/css/main.css
assets/scss/components/_button.scss
src/__snapshots__/footer.test.jsx.snap
src/forms/Button.jsx
src/forms/ToggleSwitch.jsx
src/forms/__snapshots__/button.test.jsx.snap
src/forms/button.story.jsx
src/interactive/__snapshots__/accordionPanel.test.jsx.snap
src/interactive/__snapshots__/tooltip.test.jsx.snap
src/navigation/Nav.jsx

Feature/sc 109316/fe pro dashboard accessibility fixes
