meetup/meetup-web-components

components/DateDisplay.jsx, components/datedisplay.story.jsx, components/datedisplay.test.js
Fixes https://meetup.atlassian.net/browse/MW-288
=> rename Tearsheet to DateDisplay

src/Tabs.jsx, src/tabs.test.jsx
this ensures tab class variants actually work
=> className should be applied to ul instead of nav element in Tabs

.github/PULL_REQUEST_TEMPLATE.md
Adding github template we are using in mup web to this repo to make PR generation easier :)
=> Adding a github template

package.json
the ongoing saga of dependency cleanup
=> set peerDependencies / devDependencies

package.json
=> build source maps

package.json, yarn.lock
Greenkeeper Monday branch
Closes #71 
Closes #72
=> Gk mondays/feb 13 2017

.eslintrc.js, .yarnrc, README.md, package.json
I accidentally already added a `yarn.lock` file with my Greenkeeper Monday tasks yesterday, but this completes the task. It also adds the eslint precommit hook at @eilinora 's request.
=> Move from npm to yarn

package.json, yarn.lock
required for precommit hook to work thats already in package.json
=> add husky module

package.json, yarn.lock
=> Greenkeeper - feb21

package.json
=> greenkeeper 6 march 17

yarn.lock
=> fix yarn lock

.travis.yml
=> check yarn.lock

.travis.yml
=> travis to node v7.7.1

assets/scss/components/_flex.scss, package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-212
Update `swarm-sasstools` to get updated signature for `_bpModifier` that allows us to generate "atAll" breakpoint classes. 
See also: https://github.com/meetup/swarm-sasstools/blob/master/scss/utils/helpers/_pcv-modifier.scss#L54
=> Sds 212/fix at all flex classes

assets/scss/components/_bounds.scss, src/Bounds.jsx, src/bounds.story.jsx, src/bounds.test.jsx
fixed Sass var for normal bounds max-width
=> set normal bounds to normal bounds width

src/Tabs.jsx, src/tabs.test.jsx
DoD:
- TabsTab should add `prop.className` to `className` list + tests
=> Adding classname for tabstab + tests

src/GridList.jsx
`<ul> <li>` instead of `<ul> <div>`
=> Easy: rendered html tag fix in GridList

package.json, yarn.lock
=> yarn upgrade-interactive 27 march 2017

assets/scss/components/_all.scss, assets/scss/components/_hscroll.scss, src/Hscroll.jsx, src/hscroll.story.jsx, src/hscroll.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-224
Adds SQ2-like `Hscroll` component with media-conditional unclip prop
=> add Hscroll component

README.md
=> added line to help the uninitiated (me :)

src/RsvpBox.jsx
missed the update to the button import
=> Fix import path in RsvpBox

assets/scss/components/_tabs.scss
Fixes https://meetup.atlassian.net/browse/MW-844
Updated style of tabs to match what @rxb has been working with most recently.
=> Changed tabs to new style

.travis.yml
=> travis - no sudo

package.json
- watch tests while you develop!
- but don't break the travis unit tests command!
- un-silent our tests when we're not doing a travis build!
=> create base test class that is not silent, add test watch class

src/forms/TextInput.jsx, src/forms/textInput.story.jsx, src/forms/textInput.test.jsx
https://meetup.atlassian.net/browse/MUP-10166
=> Add search input option for text input component

package.json, yarn.lock
Repo notes:
```
react-router - keep on 3.0.2
```
=> Yarn Upgrade April 24

src/forms/Textarea.jsx, src/forms/textarea.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-45
- adding value prop to text area
=> WC-45: adding value prop to textarea

assets/scss/components/_button.scss
Fixes [SDS-256](https://meetup.atlassian.net/browse/SDS-256), needed for work on [MW-894](https://meetup.atlassian.net/browse/MW-894)
Removed bg color for button--reset[disabled]
=> Removed bg color for button--reset[disabled]

assets/scss/components/_avatar.scss, package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-243
Avatars scale at the same rate we scale type and ([soon](https://github.com/meetup/meetup-web-components/pull/163)) icons
NOTE: This will break `AvatarRow` in `mup-web` - will need to update `height` to also use responsive media variables
=> Responsive avatars

src/layout/Section.jsx, src/layout/section.test.jsx
=> Fixed typo and test for Section

package.json, src/layout/SectionTitle.jsx, src/layout/bounds.story.jsx, src/layout/chunk.story.jsx, src/layout/section.story.jsx, src/layout/sectionTitle.test.jsx, src/layout/stripe.story.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-282
Using new type scale for our components
=> new type scale in MWC

src/interactive/Modal.jsx
updating so that closeArea isnt be added to div with ...other by pulling off of props
=> Modal showing console errors

src/media/Icon.jsx, src/utils/components/withMatchMedia.jsx, src/utils/components/withMatchMedia.story.jsx, src/utils/components/withMatchMedia.test.jsx, src/utils/designConstants.js
Fixes https://meetup.atlassian.net/browse/WC-49
Adds higher order component that provides boolean `isAt[breakpoint]Up` props to wrapped component.
=> Wc 49/match media hoc utility

src/layout/flex.story.jsx, src/layout/flexItem.story.jsx
Fixes https://meetup.atlassian.net/browse/WC-59
Adds `InfoWrapper` documentation to `Flex` and `FlexItem` stories.
=> Wc 59/flex infowrappers

src/media/Icon.jsx, src/media/icon.test.jsx
Fixes https://meetup.atlassian.net/browse/MW-1238
DoD:
- Set small icon style to use thin icon styles
=> MW-1238: Adding thin icon style for small Icons

src/utils/components/withMatchMedia.jsx, src/utils/components/withMatchMedia.story.jsx, src/utils/components/withMatchMedia.test.jsx
file didn't have a default export
=> fixing export of withMatchMedia

src/forms/Button.jsx, src/forms/button.story.jsx
=> Centering button copy

package.json, yarn.lock
=> SV: updating sass icons refs

package.json
=> move swarm-icons from dependency to devDependency

package.json
=> Package.json - Update swarm icons version

src/forms/TextInput.jsx, src/forms/textInput.story.jsx
Fixes https://meetup.atlassian.net/browse/WC-69
Text inputs aren't doing placeholder rendering. 
And after some discussion it is recommended not to do anything with International Provider in storybook, so I'll remove.
If I should do this another way let me know!
=> adding placeholder rendering and shouldn't use IntlProvider in tests

src/media/Icon.jsx, src/media/icon.story.jsx, src/utils/designConstants.js
Fixes https://meetup.atlassian.net/browse/SDS-350
Recent designs have called for an even smaller icon size. e.g.: - icons in buttons, "like" heart on comments
=> Added xxs media size to be used only for icons

assets/scss/components/_forms.scss, package.json, src/forms/Checkbox.jsx, src/forms/__snapshots__/checkbox.test.jsx.snap, src/forms/checkbox.story.jsx, src/forms/checkbox.test.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-349
Updated checkbox style to match latest visual design updates from Chris and Max. Radios coming soon...
From Sketch:
From Storybook:
=> Updated checkbox visual design

src/layout/GridList.jsx, src/layout/gridList.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-384
is wrapping content in hscroll when we want auto height content
=> SDS-384: adjusting gridlist to not always wrap unless specified

assets/scss/components/_button.scss, src/forms/TogglePill.jsx, src/forms/button.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-351
Update button styles based on new decisions made by Max B and Chris. Background colors will be correct once we start to use `swarm-constants` instead of `meetup-swatches`.
=> Button style tweaks

assets/scss/components/_tabs.scss, src/interactive/Tabs.jsx, src/interactive/tabs.story.jsx, src/interactive/tabs.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-375
Cosmetic updates to tabs, border at the bottom of all tabs is now default
=> Updated tab styles

assets/scss/components/_groupCard.scss
Fixes https://meetup.atlassian.net/browse/SDS-381
Changes card border and weight to match Chris' designs
=> Lighten card borders

assets/scss/components/_avatar.scss, src/media/Avatar.jsx, src/media/avatar.story.jsx, src/media/avatar.test.js
Fixes https://meetup.atlassian.net/browse/SDS-364
Added a `large` avatar size. Marking as prelim because I would prefer to use `$media-l`, but have to check with Chris first
=> Added a large avatar size option

src/forms/SelectInput.jsx
Fixes https://meetup.atlassian.net/browse/MW-1831
This PR simply updates the `SelectInput` component state whenever `props` change. Currently if the value changes, the component state won't update and it will cause issues with the view. See: https://medium.com/@justintulk/react-anti-patterns-props-in-initial-state-28687846cc2e
=> SelectInput - Sync component props and state 👏

src/forms/redux-form/Textarea.jsx, src/forms/redux-form/__snapshots__/textarea.test.jsx.snap, src/forms/redux-form/textarea.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-81
=> WC-81: Move Redux Form Textarea into MWC

src/forms/timeInput.story.jsx
Fixes https://meetup.atlassian.net/browse/WC-85
Now that the TimeInput has no state and is an uncontrolled component,  `defaultValue` should be used to set a value on the component in storybook.
https://facebook.github.io/react/docs/uncontrolled-components.html#default-values
Right now when a value is set, you cannot interact with the field and it seems broken.
=> use defaultValue and import infowrapper

src/utils/components/withMatchMedia.jsx, src/utils/components/withMatchMedia.test.jsx
Fixes https://meetup.atlassian.net/browse/MW-1915
does the thing that makes snapshots legible.
=> set displayname on the withmatchmedia class

.travis.yml, assets/scss/components/_calendar.scss, src/forms/CalendarComponent.jsx, src/forms/calendarComponent.story.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/WC-88
style changes for our calendar component. see ticket for specs.
=> Wc 88 calendar style changes

package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/MW-1988
=> MW-1988: update swarm icons

src/forms/Checkbox.jsx, src/forms/checkbox.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-423
=> Add onChange prop to Checkbox

README.md
adding some docs about redux form
=> Redux form documentation

src/forms/SelectInput.jsx
Fixes https://meetup.atlassian.net/browse/SDS-434
=> SDS-434: safeguard for when options array is empty

src/forms/redux-form/SelectInput.jsx
Fixes https://meetup.atlassian.net/browse/SDS-437
ReduxForm sends certain attributes through the `input` prop.
=> SDS-437: selectinput spreads input from reduxform

assets/scss/components/_accordion.scss, src/interactive/AccordionPanel.jsx, src/interactive/AccordionPanelGroup.jsx, src/interactive/accordion.story.jsx, src/interactive/accordion.test.jsx, src/utils/WithToggleControl.jsx
Reverts meetup/meetup-web-components#309
=> Revert "Accordion - added the ability to have a toggle control instead of icon"

assets/scss/components/_all.scss, assets/scss/components/_toggleSwitch.scss, src/forms/ToggleSwitch.jsx, src/forms/__snapshots__/toggleSwitch.test.jsx.snap, src/forms/toggleSwitch.story.jsx, src/forms/toggleSwitch.test.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/WC-103_add_toggleSwitch
Adding a form input that looks like a native mobile toggle switch
=> Added a ToggleSwitch component

src/forms/redux-form/Checkbox.jsx, src/forms/redux-form/__snapshots__/checkbox.test.jsx.snap, src/forms/redux-form/checkbox.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-108
Redux. Form. Checkbox.
=> Wc 108 reduxform checkbox

assets/scss/components/_forms.scss, package.json, src/forms/CalendarComponent.jsx, src/forms/DateTimeLocalInput.jsx, src/forms/NumberInput.jsx, src/forms/SelectInput.jsx, src/forms/TextInput.jsx, src/forms/Textarea.jsx, src/forms/TimeInput.jsx, src/forms/__snapshots__/selectInput.test.jsx.snap, src/forms/__snapshots__/textInput.test.jsx.snap, src/forms/selectInput.story.jsx, src/forms/textInput.story.jsx, yarn.lock
Re: Prelim label - will remove once:
Fixes https://meetup.atlassian.net/browse/SDS-426
Updating form styles per Natalia's [designs for Event Create](https://meetup.atlassian.net/wiki/spaces/SPARK/pages/114885378/Event+Create+Text+input+fields)
=> Updated default form styles

src/forms/RadioButton.jsx, src/forms/__snapshots__/radioButton.test.jsx.snap
Fixes https://meetup.atlassian.net/browse/MUP-15718
In the "When members join" section, spacing is off in IE. See screenshot.
To repro:
Using latest Internet Explorer
Go to pro.meetup.com/pro/auto-19/admin/chapters
Expand "Edit groups"
See section to right, "When members join"
Note that spacing is weird on radios
=> MUP-15718 Radio Button Group Update

src/forms/SelectInput.jsx, src/forms/__snapshots__/selectInput.test.jsx.snap, src/forms/selectInput.story.jsx, src/forms/selectInput.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-120
=> add disabled attribute to Select input options

assets/scss/components/_toast.scss
Replaced hard-coded colors with swarm-constants colors
=> Toast bg color bugfix

src/interactive/Toast.jsx, src/interactive/toast.story.jsx, src/interactive/toast.test.jsx
adds ability to run js function on dismiss of a toast
=> add toast onDismiss

src/interactive/AccordionPanel.jsx, src/interactive/accordion.story.jsx, src/interactive/accordionPanel.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-122
adding a callback fro when a panel is clicked. We need a way to know if a panel is open/active for Event Schedule.
=> Wc 122 accordion panel click callback

src/forms/CalendarComponent.jsx, src/forms/__snapshots__/calendarComponent.test.jsx.snap
=> Our lord and savior, div.

src/forms/CalendarComponent.jsx
We will catch them in the app instead.
=> Remove errors from the calendar component.

src/interactive/AccordionPanel.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/accordion.story.jsx, src/interactive/accordionPanel.test.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/WC-128
Gives mwc consumers the option to override the AccordionPanel click handler (typically `this._handleToggle`) by passing a prop into AccordionPanel. This freezes the panel in it's current state, preventing users from being able to toggle panels on or off, and calls whatever custom function is passed into `onToggleClick`.
=> Custom click handler for clicking AccordionPanel's ToggleSwitch

CHANGELOG.md, Makefile, src/forms/Checkbox.jsx, src/forms/redux-form/NumberInput.jsx, src/forms/redux-form/__snapshots__/numberInput.test.jsx.snap, src/forms/redux-form/numberInput.test.jsx
Fixes https://meetup.atlassian.net/browse/MW-2509
a NumberInput that can be used with Redux-Form
=> redux-form-compatible NumberInput

src/forms/CalendarComponent.jsx, src/forms/__snapshots__/calendarComponent.test.jsx.snap, src/forms/calendarComponent.test.jsx
Fixes https://meetup.atlassian.net/browse/WP-588
error prop needs to be handled
=> add error output to `CalendarComponent`

assets/scss/components/_button.scss
=> Increased padding for button label when icon is present

src/forms/TimeInput.jsx
Fixes https://meetup.atlassian.net/browse/WC-135
Fixes time calc math. Prevents infinite loop.
=> WC-135: formatHours fixes, no hanging

src/types.js
Start of exporting proptypes for properties that are injected by mwc code
=> Media PropType

src/forms/TimeInput.jsx
Fixes https://meetup.atlassian.net/browse/WC-136
=> Wc 136 timeinput callback

src/forms/TextInput.jsx
Fixes https://meetup.atlassian.net/browse/WC-139
display errors but allow people to overtype in input. remove maxlength attr.
=> dont set maxlen of field

assets/scss/components/_button.scss
=> Smaller border-radius for buttons

src/interactive/popover.story.jsx, src/interactive/tabs.story.jsx, src/utils/storyComponents.js
Fixes https://meetup.atlassian.net/browse/WC-142
Replaces `Link` from `react-router-dom`with `StoryLink`, a component that renders an anchor tag and disables link following.
=> replace Link components with StoryLink

src/interactive/Dropdown.jsx
=> rm extraneous console.log

assets/scss/components/_dropdown.scss
=> Bump z-index of dropdown-content

assets/scss/components/_dropdown.scss, src/interactive/Dropdown.jsx
=> improve right alignment for dropdown

assets/scss/components/_dropdown.scss, src/interactive/Dropdown.jsx, src/interactive/__snapshots__/dropdown.test.jsx.snap, src/interactive/dropdown.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-491
Sometimes we don't want a dropdown to portal. E.g.: if a <Dropdown> contains components that also portal
=> Optional portalling for Dropdown

src/interactive/Dropdown.jsx, src/interactive/__snapshots__/dropdown.test.jsx.snap, src/interactive/dropdown.story.jsx
Addresses feedback from Mike M
=> Changed shouldPortal prop to noPortal

assets/scss/components/_tabs.scss, src/interactive/Tabs.jsx, src/interactive/tabs.story.jsx
Fixes https://meetup.atlassian.net/browse/WC-159
Adds support for vertical tabs
=> Vertical tab support

src/forms/ToggleSwitch.jsx, src/forms/redux-form/__snapshots__/textarea.test.jsx.snap, src/forms/redux-form/textarea.test.jsx, src/forms/textarea.test.jsx, src/forms/toggleSwitch.test.jsx, src/hscroll.test.jsx, src/interactive/Dropdown.jsx, src/interactive/dropdown.test.jsx, src/interactive/modal.test.js, src/layout/sectionTitle.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-155
Fixed the warnings happening in unit tests
=> Fix warnings in unit tests

Makefile, README.md, assets/scss/components/_avatar.scss, assets/scss/components/_card.scss, assets/scss/components/_chunk.scss, assets/scss/components/_flex.scss, assets/scss/components/_gridList.scss, assets/scss/components/_inlineblockList.scss, assets/scss/components/_section.scss, assets/scss/components/_tabs.scss, package.json, yarn.lock
Replaced `responsiveVarContext--*` usage with custom properties
=> Upgrade sasstools to reduce compiled CSS size

assets/scss/components/_inlineblockList.scss
Fixes https://meetup.atlassian.net/browse/WC-163
=> WC-163: fix inline block bug

package.json, src/interactive/Dropdown.jsx, yarn.lock
Re Prelim tag:
* Not sure if third-party util is the right way to go
* `this.scheduleUpdate` is defined in the constructor instead of just being bound. The only other place we do this is `AccordionPanel`, but it wouldn't work any other way - is that ok?'
Fixes https://meetup.atlassian.net/browse/WC-154
I decided to go with a third-party package instead of rolling our own. React references it in their documentation, so I think it's safe.
I also found and fixed a defect where `dropdown-content` would be incorrectly when scrolling horizontally and portalling
=> Added requestAnimationFrame utility

assets/scss/components/_dropdown.scss, src/interactive/Dropdown.jsx
Fixes https://meetup.atlassian.net/browse/MW-3142
=> Reduced zindex of dropdown, fixed noPortal bugs

assets/scss/components/_dropdown.scss, package.json, yarn.lock
=> fixed typos

src/interactive/Modal.jsx, src/interactive/modal.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-498
=> SDS-498: add max height to fixed modals that take margin into account

assets/scss/components/_dropdown.scss, src/interactive/Dropdown.jsx
Fixes https://meetup.atlassian.net/browse/MW-3252
* Better align the dropdown pointer
* Menu item hover states
* Avoid text wrapping (may end up having to be done in mup-web, but I'll see what I can do)
* Make the cursor a pointer for menu items
=> Design improvements to <Dropdown>

src/media/Icon.jsx
Fixes https://meetup.atlassian.net/browse/WC-176
Now the `color` prop shows up when you click "Show Info"
=> Added color proptype to Icon

README.md
Fixes https://meetup.atlassian.net/browse/SDS-505
A list of criteria that we check for anyway when reviewing PRs. This should also be added somewhere [swarm-design-system](https://meetup.github.io/swarm-design-system/)  - probably somewhere in the Components tab?
=> Document guidelines for adding new components

assets/scss/components/_hscroll.scss, src/Hscroll.jsx, src/__snapshots__/hscroll.test.jsx.snap, src/hscroll.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-168
Before:
After:
=> Hide left gradient on hscroll until scrolled

src/Footer.jsx, src/footer.story.jsx
Fixes https://meetup.atlassian.net/browse/WC-184
Added default props to `<Footer>` to make sure it can be rendered without providing props
=> Added defaultProps to Footer component

src/Footer.jsx, src/__snapshots__/footer.test.jsx.snap, src/footer.story.jsx, src/footer.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-187
Instead of requiring engineers to pass in their own AppBadges component, the Footer component imports it's own.
=> Added AppBadges to the Footer

src/media/AppBadges.jsx
=> Fix AppBadge proptypes

assets/scss/components/_button.scss, src/forms/button.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-531
Before, bordered buttons would appear to respond to being hovered when they were disabled
=> Fix disabled bordered button styles

assets/scss/components/_calendar.scss
Fixes https://meetup.atlassian.net/browse/WC-180
Instead of importing all the Flatpickr CSS, I refactored the styles and kept them in `_calendar.scss`
=> Reduce flatpickr CSS bloat

package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/WC195
=> add lint-staged

package.json, src/footer.story.jsx, src/forms/button.story.jsx, src/forms/calendarComponent.story.jsx, src/forms/checkbox.story.jsx, src/forms/numberInput.story.jsx, src/forms/selectInput.story.jsx, src/forms/textInput.story.jsx, src/forms/textarea.story.jsx, src/forms/toggleSwitch.story.jsx, src/forms/togglepill.story.jsx, src/hscroll.story.jsx, src/interactive/accordion.story.jsx, src/interactive/dropdown.story.jsx, src/interactive/tabs.story.jsx, src/interactive/toast.story.jsx, src/layout/card.story.jsx, src/media/appBadges.story.jsx, src/media/avatar.story.jsx, src/media/avatarmember.story.jsx, src/media/icon.story.jsx, src/navigation/navbar.story.jsx, src/utils/components/withToggleControl.story.jsx, src/utils/decorators.jsx
Fixes https://meetup.atlassian.net/browse/SDS-540
=> rm react-intl

assets/scss/components/_card.scss
Fixes https://meetup.atlassian.net/browse/SDS-550
=> fix card left and right flushing

src/layout/flex.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-551
=> Correct Flex story vertical alignment for IE11

assets/scss/components/_forms.scss, src/layout/stripe.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-558
=> Remove SelectInput dotted focus outline in FF

package.json, src/forms/Button.jsx, src/forms/button.story.jsx, src/forms/button.test.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, yarn.lock
Fixes https://meetup.atlassian.net/browse/WC-174
Let buttons render as `<a>` or `<Link>`, and tell them where to go with a `link` prop
=> Optionally render button with anchor or Link tag

src/forms/CharCounter.jsx, src/forms/TextInput.jsx, src/forms/Textarea.jsx, src/forms/__snapshots__/charCounter.test.jsx.snap, src/forms/charCounter.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-197
- Adds `CharCounter` component that changes to error color when user overtypes.
=> Wc 197/char counter component

src/forms/Button.jsx, src/forms/button.story.jsx, src/forms/button.test.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap
Fixes https://meetup.atlassian.net/browse/WC-199
rm `React.cloneElement` usage per Mike M's feedback on https://github.com/meetup/meetup-web-components/pull/444#pullrequestreview-102802246
=> Clean up `Button`component JSX

src/forms/TextInput.jsx, src/forms/__snapshots__/textInput.test.jsx.snap, src/forms/textInput.story.jsx, src/forms/textInput.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-202
No more "undefined" as a validation message - now we only set a custom validity message for the browser-native form validation if one is provided.
=> improve how we set custom validity, update tests

assets/scss/components/_button.scss, src/forms/Button.jsx, src/forms/button.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-565
=> Don't let disabled buttons call onClick

assets/scss/components/_all.scss, assets/scss/components/_signup.scss, assets/svg/logo_google.svg, src/SignupModal.jsx, src/SignupModal.test.jsx, src/__snapshots__/SignupModal.test.jsx.snap, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/notifications/NotificationsDropdown.jsx, src/navigation/components/profile/ProfileDropdown.jsx, src/navigation/components/profile/ProfileDropdown.test.jsx, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, src/navigation/nav.story.jsx, src/signupModal.story.jsx
Fixes https://meetup.atlassian.net/browse/MP-587
Currently, the MWC navigation component doesn't handle sign-up functionality.
DOD:
- Add Functionality to Sign-up
Do tiny fixes:
- Fix See All Groups Link
- Fix Logo Link
- Fix Profile Link
- Flow Error for the Notification Dropdown
=> Signup functionality (MP-587)

assets/scss/components/_togglePill.scss
Came from PR feedback on https://github.com/meetup/mup-web/pull/2802
=> TogglePill style hotfix

assets/scss/components/_footer.scss, package.json, src/__snapshots__/SignupModal.test.jsx.snap, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-564
Removed extra styling, upgraded sasstools
=> Prevent double border on footer link

src/forms/TimeInput.jsx, src/interactive/AccordionPanel.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap, src/interactive/accordionPanelGroup.test.jsx, src/utils/components/withErrorList.jsx
killing accordion panel noise about button in buttons + error list props being boolean
=> Console Noise Killer Pt2

src/forms/CalendarComponent.jsx, src/forms/ErrorList.jsx, src/forms/TimeInput.jsx
added bool to 3 more components
=> Console error :skull: so close

assets/scss/components/_calendar.scss
=> Flatpickr weekdays layout fix

assets/scss/components/_button.scss, package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/WC-213
=> Un-set font size for <Button reset />

.travis.yml
Remove broken ssh auth from travis config
=> rm ssh keys from travis config

package.json, yarn.lock
=> Bumped swarm-icons version number

assets/scss/components/_all.scss, assets/scss/components/_dropdown.scss, assets/scss/components/_tooltip.scss, src/interactive/Dropdown.jsx, src/interactive/Tooltip.jsx, src/interactive/tooltip.story.jsx, src/interactive/tooltip.test.jsx, src/utils/components/FloatingPosition.jsx, src/utils/components/__snapshots__/floatingPosition.test.jsx.snap, src/utils/components/floatingPosition.test.jsx
Fixes https://meetup.atlassian.net/browse/MUP-19431
Added a `Tooltip` component that gets it's positioning from a new wrapper component, `FloatingPosition`.
There's a [follow-up ticket](https://meetup.atlassian.net/browse/SDS-587) to replace the positioning code in `Dropdown.jsx` by wrapping the dropdown content in `<FloatingPosition />`
=> Tooltip component

src/navigation/Nav.jsx, src/navigation/Nav.test.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/nav.story.jsx
Fixes https://meetup.atlassian.net/browse/MP-864
Notifications panel stucks in constant loading state if there are no notifications
=> fixing notifications error: notifications stuck in constant loading state

src/forms/CalendarComponent.jsx, src/forms/TimeInput.jsx
=> Let CalendarComponent and TimeInput take classnames for label

src/forms/SelectInput.jsx, src/forms/selectInput.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-591
=> Allow for setting of the ID attribute separately from NAME attribute in SelectInput

src/interactive/Dropdown.jsx, src/interactive/dropdown.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-587
Now Dropdown and Tooltip get positioned the same way. While I was in here, I also fixed keyboard navigation for a Dropdown with `menuItems`
=> Replaced Dropdown positioning code with FloatingPosition wrapper

src/navigation/Nav.jsx
Fixes https://meetup.atlassian.net/browse/MP-903
Updating navbar to load data fro notifications/groups when it is not loaded.
=> navbar notifications/groups fix. Loading data when data is not loaded yet.

src/forms/TogglePill.jsx
Heart icon wasn't updating because it was trying to use `isActive` prop, not the dynamic `isActive` render prop.
=> Fix TogglePill topic variant - icon shape toggle

src/__snapshots__/footer.test.jsx.snap, src/utils/getSocialLinks.js
Fixes https://meetup.atlassian.net/browse/WC-220
Adds link to our `pl-PL` Twitter page.
=> Adding pl-PL twitter link

src/interactive/Dropdown.jsx
Remove weird onSelect prop, add prop to Dropdown to accept Downshift props, pass item props into each dropdown item
=> Dropdown hotfix

src/media/Loading.jsx, src/media/__snapshots__/loading.test.jsx.snap
Fixes invalid prop warnings for SVG circle
=> fix svg property warnings in Loading

src/forms/redux-form/CalendarComponent.jsx, src/forms/redux-form/NumberInput.jsx, src/forms/redux-form/SelectInput.jsx, src/forms/redux-form/TextInput.jsx, src/forms/redux-form/Textarea.jsx, src/forms/redux-form/TimeInput.jsx, src/forms/redux-form/selectInput.test.jsx, src/interactive/__snapshots__/tooltip.test.jsx.snap, src/interactive/tooltip.test.jsx, src/navigation/components/notifications/Notifications.test.jsx, src/utils/components/ToggleWrapper.jsx, src/utils/components/__snapshots__/toggleWrapper.test.jsx.snap, src/utils/components/toggleWrapper.test.jsx, src/utils/components/withLoading.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-599
Made a few changes, such as updating PropTypes and the way some props are passed, to quiet the warnings in component tests.
=> Clean up warnings in tests

src/utils/components/FloatingPosition.jsx, src/utils/components/__snapshots__/floatingPosition.test.jsx.snap, src/utils/components/floatingPosition.test.jsx
- Positioning functions actually unbind on unmount, prevent the `forceUpdate` error from being thrown
- Return if `getContent()` like we do with `getTrigger()` to prevent the error about `getClientRect` being null
=> Fix errors in FloatingPosition

src/forms/ToggleSwitch.jsx, src/interactive/AccordionPanel.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap
Updated some of the attributes in AccordionPanel in order to:
- Have a better screenreader experience
- Make sure elements are still selectable if somebody passes a number into the `id`
=> Update some el attrs in AccordionPanel

.travis.yml
=> reenable git tagging

assets/scss/components/_typeahead.scss, src/forms/Typeahead.jsx, src/forms/TypeaheadItem.jsx, src/forms/typeahead.story.jsx, src/forms/typeahead.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-226
Allows a user to select multiple items and provides a prop to open the Typeahead menu on focus
=> Typeahead multiselect

assets/scss/components/_modal.scss
=> Per Farah's feedback - subtler focus styles for modal close button

assets/scss/helpers/_popup.scss
Fixes https://meetup.atlassian.net/browse/MG-1395
Adjusted cascade and changed the way we do `transform: translateX(0)` to right-position popup contnet
=> Fix modals within dropdowns

src/interactive/Modal.jsx
=> Correct Modal PropTypes

assets/scss/components/_tooltip.scss, src/interactive/Tooltip.jsx, src/interactive/__snapshots__/tooltip.test.jsx.snap, src/interactive/tooltip.story.jsx, src/interactive/tooltip.test.jsx
Fixes https://meetup.atlassian.net/browse/WC-231
Added a variant of Tooltip that provides its own close button
=> Tooltip with a close button

assets/scss/components/_navbar.scss, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/nav.story.jsx
Fixes https://meetup.atlassian.net/browse/MP-1249
There no "Create a Meetup" link in the navbar component, this PR adds one
=> Mp 1249 create meetup link

src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap
Fixes https://meetup.atlassian.net/browse/MP-1249
Adding create a meetup for auth non-pro users
=> adding create for auth users

src/utils/components/FloatingPosition.jsx
Initializing align state with align prop instead of a hard-coded value
=> Fix Dropdown popup misalignment

.prettierignore, .prettierrc, package.json
Fixes https://meetup.atlassian.net/browse/SDS-650
To preview what Prettier would do to our code, run `yarn lint:prettier --write` and open the files Prettier prints in the command line.
=> Configure Prettier for SCSS and JS

assets/scss/components/_togglePill.scss, src/forms/TogglePill.jsx, src/forms/__snapshots__/togglePill.test.jsx.snap, src/forms/togglePill.test.jsx, src/forms/togglepill.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-661
The design team no longer wants or needs a `large` variant of the `TogglePill`
=> Removed `large` variant of TogglePill

assets/scss/components/_all.scss, assets/scss/components/_infoToggle.scss, src/interactive/Dropdown.jsx, src/interactive/InfoToggle.jsx, src/interactive/Tooltip.jsx, src/interactive/__snapshots__/infoToggle.test.jsx.snap, src/interactive/__snapshots__/tooltip.test.jsx.snap, src/interactive/dropdown.story.jsx, src/interactive/infoToggle.story.jsx, src/interactive/infoToggle.test.jsx, src/interactive/tooltip.story.jsx, src/utils/components/FloatingPosition.jsx, src/utils/components/__snapshots__/floatingPosition.test.jsx.snap
Fixes https://meetup.atlassian.net/browse/SDS-639
Added a component to support the info tooltip pattern we've been seeing a lot of lately. This will replace [InfoTooltip in mup-web](https://github.com/meetup/mup-web/blob/c3219b603abd77e7635baf521a260da793553499/src/components/InfoTooltip.jsx)
=> Added InfoToggle component

assets/scss/components/_gridList.scss
=> Full height autoheight grid cells

assets/scss/components/_forms.scss
Fixes https://meetup.atlassian.net/browse/SDS-664
Before:
After:
=> Fix field--reset styles

package.json
Fixes https://meetup.atlassian.net/browse/WC-222
Added lint-staged tasks for prettier and stylelint
=> Added Prettier and Stylelint tasks to lint-staged

src/forms/NumberInput.jsx, src/forms/numberInput.story.jsx
Fixes https://meetup.atlassian.net/browse/WC-242
Replaced deprecated methods `componentWillReceiveProps` and `componentWillUpdate` with static `getDerivedPropsFromState` method
=> NumberInput React 17

src/Footer.jsx, src/__snapshots__/footer.test.jsx.snap
Fixes https://meetup.atlassian.net/browse/WC-244
=> [WC-244] Adds a header to social links section in footer

package.json, src/forms/Textarea.jsx, src/forms/textarea.test.jsx, yarn.lock
Exposes ref to Textarea component so developers have access to the raw textarea element.
=> expose ref to textarea component

src/__snapshots__/footer.test.jsx.snap, src/utils/getSocialLinks.js
Fixes https://meetup.atlassian.net/browse/WC-245
=> [WC-245] Updates social links internationalization

package.json, src/forms/TextInput.jsx
Fixing icon being read by screenreader + flowing while i'm here
=> Fixing aria reading icon + flowing

.flowconfig, assets/scss/components/_modal.scss, src/interactive/Modal.jsx
Fixes https://meetup.atlassian.net/browse/SDS-721
Styles for fullscreen modal were missing, so it was just rendering directly into the page.
=> Added styles for fullscreen modal

package.json, yarn.lock
updating swarm icons so i can update mupweb :)
=> [SV] updating swarm icons library

src/interactive/AccordionPanel.jsx, src/interactive/AccordionPanelGroup.jsx, src/interactive/accordion.story.jsx, src/interactive/accordionPanelGroup.test.jsx
There was a weird race condition issue that was happening from the original implementation of the AccordionGroup component. This resolves all the race condition issues except one issue that isn't currently being used in mup-web or pro-web.
Will follow up to fix.
=> Fix accordion race condition

.stylelintrc, assets/scss/components/_accentHeader.scss, assets/scss/components/_avatar.scss, assets/scss/components/_button.scss, assets/scss/components/_calendar.scss, assets/scss/components/_card.scss, assets/scss/components/_chunk.scss, assets/scss/components/_dropdown.scss, assets/scss/components/_flex.scss, assets/scss/components/_gridList.scss, assets/scss/components/_hscroll.scss, assets/scss/components/_icon.scss, assets/scss/components/_inlineblockList.scss, assets/scss/components/_modal.scss, assets/scss/components/_navbar.scss, assets/scss/components/_section.scss, assets/scss/components/_stripe.scss, assets/scss/components/_tabs.scss, assets/scss/components/_togglePill.scss, package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-720
Replaced Bourbon mixins with regular CSS and upgraded sasstools dependency/peer-dependency
=> Remove Bourbon dependency

package.json, yarn.lock
=> Update sasstools peerdep

package.json, src/forms/Typeahead.jsx
Updating component to handle aria props of list items + adding updatesnapshot call
=> fixing roles and html types for aria to read/pick up items correctly

src/interactive/accordion.story.jsx
=> Fix toggleswitch accordion story

package.json, src/SignupModal.jsx, src/forms/ToggleSwitch.jsx, src/interactive/Dropdown.jsx, src/media/Loading.jsx, src/navigation/components/profile/ProfileDropdown.jsx, src/utils/designConstants.js, yarn.lock
Fixes https://meetup.atlassian.net/browse/WC-247
=> Upgrade constants to 2.x

src/forms/redux-form/NumberInput.jsx, src/forms/redux-form/__snapshots__/numberInput.test.jsx.snap
wasn't updated based on numberinput changes
=> [SV] hotfix redux number input

src/forms/RadioButtonGroup.jsx, src/forms/__snapshots__/radioButtonGroup.test.jsx.snap, src/forms/radioButtonGroup.test.jsx
Related to https://meetup.atlassian.net/browse/MG-2470
Adds wrapping support on RadioButtonGroup, which uses a `Flex` component that already has wrapping built in.
=> Adds support for wrapping on RadioButtonGroup

src/navigation/Nav.jsx, src/navigation/Nav.test.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/nav.story.jsx
Fixes https://meetup.atlassian.net/browse/MP-1866
Update the Nav component to use `is_pro_admin` from self
=> MP-1866 update component to use is_pro_admin from self

src/forms/selectInput.story.jsx
SelectInput was being imported to the story destructured, but we export `SelectInput` as default
=> Fix SelectInput default story

src/navigation/Nav.jsx
=> mark all notification as read when clicked on Notification

src/navigation/Nav.jsx
=> improvements

src/navigation/Nav.jsx
=> PYMT-157: Should mark notifications as read on the `mediumup` size screens 

src/navigation/Nav.jsx
=> PYMT-157: Applied linter formatting

src/navigation/Nav.jsx
=> update notifications list sort method

src/interactive/Tooltip.jsx, src/interactive/infoToggle.story.jsx, src/interactive/tooltip.story.jsx
Fixes https://meetup.atlassian.net/browse/MG-2364
Address some PR feedback, as well as passing along the event object from the original onClose.
=> update tooltip component

src/interactive/Tooltip.jsx
Fixes https://meetup.atlassian.net/browse/MAW-903
removes the ability to close a tooltip by clicking outside of it
=> remove tooltip close shim

README.md
In Yarn `install` has been replaced with `add` to add new dependencies.
=> updated command for updating mwc version

package.json, src/interactive/InfoToggle.jsx, src/interactive/infoToggle.test.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/MG-2145
fix propagation on tooltip click
=> fix event propagation on tooltip

src/forms/Select.jsx, src/forms/__snapshots__/select.test.jsx.snap
- goal is to make it more flexible for styling
- no visual change
=> Adding className option + wrapper to Select component fields

package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-679
Updates to use the version or `swarm-sasstools` with focus-within applied to cards
=> upgrading swarm-sasstools

src/forms/calendarComponent.story.jsx
Fixes https://meetup.atlassian.net/browse/SDS-730
Converted `Date` objects in  the calendar component story book to use `LocalDate` from `js-joda`
=> updated dates to use js-joda LocalDate

package.json, src/forms/Textarea.jsx, src/forms/textarea.test.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-757
Converting `<Textarea />` to use flowtype
=> flowtype textarea component

src/forms/__snapshots__/textarea.test.jsx.snap, src/forms/textarea.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-744
Updating `<Textarea />` tests to use enzyme.
=> converting Textarea component tests to enzyme

.storybook/addons.js, .storybook/config.js, flow-typed/design-system.js, package.json, src/layout/Bounds.jsx, src/layout/Card.jsx, src/layout/Chunk.jsx, src/layout/Flex.jsx, src/layout/FlexItem.jsx, src/layout/FormSection.jsx, src/layout/GridList.jsx, src/layout/InlineBlockList.jsx, src/layout/Section.jsx, src/layout/SectionTitle.jsx, src/layout/Stripe.jsx, src/layout/bounds.story.jsx, src/layout/card.story.jsx, src/layout/chunk.story.jsx, src/layout/flex.story.jsx, src/layout/flex.test.jsx, src/layout/flexItem.story.jsx, src/layout/formSection.story.jsx, src/layout/gridList.story.jsx, src/layout/inlineBlockList.story.jsx, src/layout/section.story.jsx, src/layout/sectionTitle.story.jsx, src/layout/stripe.story.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/MG-2974
Added knobs and flow types to our storybook. Hopefully this will make our components more understandable to developers!
=> MG-2974: add knobs/flow to layout components

src/navigation/components/dashboard/DashboardDropdown.jsx, src/navigation/components/dashboard/DashboardDropdown.test.jsx, src/navigation/components/dashboard/__snapshots__/DashboardDropdown.test.jsx.snap
Fixes https://meetup.atlassian.net/browse/MP-2676
Adding events link to mobile dashboard
=> adding events link to mobile dashboard

assets/css/main.css, assets/scss/main.scss, package.json, util/sassRelativeImporter.js
+ added relative importer to resolve styles from node modules
+ compiled css in new assets directory
+ build:css command added
+ main.scss created to have a 1 to 1 match of files compiled to main.css
Fixes https://meetup.atlassian.net/browse/sds-773
Exposes a compiled css file alongside the sass export in `assets`
=> CSS as exported asset

src/__snapshots__/footer.test.jsx.snap, src/forms/Checkbox.jsx
Fixes https://meetup.atlassian.net/browse/OS-260
- An an optional `iconShape` prop to Checkbox component. 
- Defaults to `check` shape.
=> Add iconShape to checkbox

.travis.yml, Makefile, assets/css/main.css, package.json
Revising the deploy routine to make it more reliable and informative
=> Wp 1053 update deploy

.travis.yml, Makefile, package.json
push tagged `npm version` commit
=> keep package.json accurate on `master`

src/navigation/Nav.jsx
Fixes https://meetup.atlassian.net/browse/OG-326
We need tracking `click` in mwp `Nav` component by adding specific className to `<a>` tag.
> Added optional linkClassName for create group nav element
=> added optional linkClassName for create group nav element

package.json, src/forms/Button.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-871
Integrates Button from swarm components into meetup-web-components
=> updating mwc to use the button component from the swarm-components

src/forms/Checkbox.jsx, src/forms/checkbox.test.jsx
Fixes https://meetup.atlassian.net/browse/<XXX-870>
- remove class based unit tests
- snapshots DID NOT need updating (weird)
- fix a bug in the Checkbox component that was causing failing tests
=> fix checkbox unit test

src/forms/RadioButton.jsx, src/forms/__snapshots__/radioButton.test.jsx.snap
Fixes https://meetup.atlassian.net/browse/SDS-873
- Use Swarm Radio component
- Update tests/snapshot
- This doesn't touch the `forms/RadioButtonGroup.jsx` and `redux-forms/RadioButtonGroup.jsx` components.
- Failing tests are from the swarm migration branch. They are unrelated to this branch.
=> Swarm v2: Migrate RadioButton to use Swarm V2 Radio

package.json, src/forms/Button.jsx, src/forms/__snapshots__/button.test.jsx.snap, src/forms/button.test.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/__snapshots__/tooltip.test.jsx.snap, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-904
Updating failing tests related to `<Button />`
=> updating button tests

package.json, src/forms/__snapshots__/textInput.test.jsx.snap, src/forms/textInput.test.jsx, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-870
Use latest swarm-components package to update and fix textInput tests.
=> Fix TextInput Tests

src/forms/Select.jsx
Adding label and helper text to select inputs in mwc using swarm label and helper components
=> adding labels within mwc

src/forms/Select.jsx
`htmlFor` specified on label
label removed from select component props
helper text text corrected
=> Bugfix select labels

src/forms/Textarea.jsx, src/forms/__snapshots__/numberInput.test.jsx.snap, src/forms/__snapshots__/select.test.jsx.snap, src/forms/__snapshots__/textarea.test.jsx.snap, src/forms/textarea.test.jsx
Fixes https://meetup.atlassian.net/browse/SDS-934
=> textarea migration

package.json, src/forms/__snapshots__/select.test.jsx.snap, yarn.lock
Taking latest swarm ui versions
=> bumping swarm ui versions

src/forms/Textarea.jsx
Destructures required text to keep it from passing it to dom
For beta build
=> destructuring required text

CHANGELOG.md, Makefile, package.json, yarn.lock
Fixes https://meetup.atlassian.net/browse/SDS-914
=> React 16.8 Upgrade

src/forms/Select.jsx, src/forms/TextInput.jsx, src/forms/Textarea.jsx, src/forms/__snapshots__/select.test.jsx.snap, src/forms/__snapshots__/textInput.test.jsx.snap, src/forms/__snapshots__/textarea.test.jsx.snap, src/forms/select.test.jsx, src/utils/a11yPassThrough.js
Fixes https://meetup.atlassian.net/browse/WP-1177
=> Wp 1177 pass a11y hidden class

.gitignore, package.json, src/forms/togglepill.story.jsx, yarn.lock
Updates packages to include swarm-ui update for togglePill "reset" prop
=> Updates swarm-ui packages to include togglePill reset prop

src/forms/Button.jsx
=> checks for component as link using props, not component name

assets/css/main.css, assets/scss/components/_navbar.scss, src/navigation/Nav.jsx
🍐 with @brookeweil 
https://www.pivotaltracker.com/story/show/166165107
https://github.com/meetup/mup-web/pull/5942
See description on [mup-web PR](https://github.com/meetup/mup-web/pull/5942).
=> Add link to Meetup Experiences to Desktop nav

assets/css/main.css, assets/scss/components/_tooltip.scss
Fixes https://www.pivotaltracker.com/story/show/166006697
Icon: 24x24
Padding: 5px
=> 166006697 Tooltip Styling

src/__snapshots__/SignupModal.test.jsx.snap, src/navigation/Nav.jsx, src/navigation/Nav.test.jsx, src/navigation/nav.story.jsx
[add GTM to signup](https://www.pivotaltracker.com/story/show/166499802)
=> implement new click handlers for signupModal in nav

assets/css/main.css, assets/scss/components/_navbar.scss, src/navigation/Nav.jsx
Refines code shipped for https://www.pivotaltracker.com/story/show/166165107
=> Tweak nav links including Experiences visibility

.flowconfig, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/profile/ProfileDropdown.jsx, src/navigation/components/profile/ProfileDropdown.test.jsx, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, src/navigation/nav.story.jsx
Fixes https://meetup.atlassian.net/browse/OS-945
https://www.pivotaltracker.com/n/projects/2346583/stories/165973896
Result:
=> OS-945: Replace `href` with our internal `Button` component

src/navigation/components/profile/ProfileDropdown.jsx
=> use a tag instead of link

src/forms/__snapshots__/numberInput.test.jsx.snap, src/forms/__snapshots__/textInput.test.jsx.snap, src/navigation/Nav.jsx, src/navigation/Nav.test.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/profile/ProfileDropdown.test.jsx, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, src/navigation/nav.story.jsx
Fixes [167054155](https://www.pivotaltracker.com/story/show/167054155)
=> 167054155 add registration gtm event to header signup modal

assets/css/main.css, assets/scss/components/_tabs.scss, src/interactive/Tabs.jsx, src/interactive/tabs.test.jsx
=> 166979381 Tabs left selector

src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/profile/ProfileDropdown.jsx, src/navigation/components/profile/ProfileDropdown.test.jsx, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, src/navigation/nav.story.jsx
Fixes https://www.pivotaltracker.com/story/show/168152159
Adds new nav dropdown element
=> 168152159: Add Payments made nav element

package.json, yarn.lock
=> upgrade beta packages

package.json, src/interactive/AdminBar.jsx, src/interactive/InfoToggle.jsx, src/interactive/Modal.jsx, src/interactive/Toast.jsx, src/interactive/Tooltip.jsx, src/interactive/__snapshots__/AdminBar.test.jsx.snap, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap, src/interactive/__snapshots__/tooltip.test.jsx.snap, src/interactive/modal.test.js, src/media/icon.test.jsx, src/navigation/components/NavItem.jsx, src/navigation/components/profile/ProfileDropdown.jsx, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, yarn.lock
https://www.pivotaltracker.com/story/show/168879802
=> Swarm migration refactor internal deps

package.json, src/interactive/AdminBar.jsx, src/interactive/InfoToggle.jsx, src/interactive/Modal.jsx, src/interactive/Toast.jsx, src/interactive/Tooltip.jsx, src/interactive/__snapshots__/AdminBar.test.jsx.snap, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap, src/interactive/__snapshots__/tooltip.test.jsx.snap, src/interactive/modal.test.js, src/media/icon.test.jsx, src/navigation/components/NavItem.jsx, src/navigation/components/profile/ProfileDropdown.jsx, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, yarn.lock
This reverts commit 2531bc553b8cf22681c9f9cf0303c5a02af38b06, reversing
changes made to abc6cf004b4a30628460339413f42a42c7bc89f1.
#	package.json
#	yarn.lock
=> Revert "Merge pull request #737 from meetup/swarm-migration-refactor-internal-deps

src/Footer.jsx, src/__snapshots__/footer.test.jsx.snap, src/footer.test.jsx
=> remove medium link and replace api link with blog link

src/Footer.jsx, src/__snapshots__/footer.test.jsx.snap
Fixes PIVOTAL-172055644
Remove WeWork from footer. Will be added to Mup-web
=> Remove WeWork from footer

src/navigation/Nav.jsx, src/navigation/Nav.test.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/search/NavbarSearch.jsx
https://www.pivotaltracker.com/story/show/172138023
=> 172138023 add search input to navbar

src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap
https://www.pivotaltracker.com/story/show/172217662
Change Search input height to 44px;
Add "Search" placeholder;
=> 172217662 adjust styling; add placeholder;

src/navigation/Nav.jsx, src/navigation/components/search/NavbarSearch.jsx
https://www.pivotaltracker.com/story/show/172217662
On mobile, when user taps on search icon and input is revealed, the input should be in focus
=> 172217662 input focus

.travis.yml, package.json
relates to https://github.com/meetup/meetup-web-platform/pull/687
=> chore(deps): bump node to 10.20.1

assets/css/main.css, assets/scss/components/_avatar.scss, assets/scss/components/_navbar.scss, package.json, src/__snapshots__/footer.test.jsx.snap, src/media/Avatar.jsx, src/media/AvatarMember.jsx, src/navigation/Nav.jsx, src/navigation/Nav.test.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/NavItem.jsx, src/navigation/nav.story.jsx, yarn.lock
Fixes [PIVOTAL-#176853926](https://www.pivotaltracker.com/n/projects/2468956/stories/176853926)
_Acceptance Criteria_
Added to Mup-Web on desktop:
-- Bell Icon for Notification to match Bell Icon on build-meetup
-- Icon for Messages to match Message Icon on build-meetup
-- Enlarged photo icon that matches that size of the photo icon on build-meetup
**_Before:_**
_**After:**_
=> new icons and enlarged avatar for new nav header

assets/css/main.css, assets/scss/components/_navbar.scss, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/NavItem.jsx, src/navigation/components/profile/ProfileDropdown.jsx, src/navigation/components/profile/ProfileDropdown.test.jsx, src/navigation/components/profile/__snapshots__/ProfileDropdown.test.jsx.snap, src/navigation/nav.story.jsx
https://www.pivotaltracker.com/story/show/176853970
This PR updates header profile dropdown to be similar to build-meetup styles
**Before**:
**After**:
=> [176853970] Update profile dropdown

assets/css/main.css, assets/scss/components/_navbar.scss, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/components/search/NavbarSearch.jsx, src/navigation/nav.story.jsx
This PR resolves: https://www.pivotaltracker.com/story/show/176853966
Main goal was to create search bar in header to be similar to build-meetup
**BEFORE**
**AFTER**
=> [176853966] Add search bar to header

src/media/AppBadges.jsx, src/media/__snapshots__/appBadges.test.jsx.snap
Fixes https://app.clubhouse.io/meetup/story/5258/change-meetup-links-from-http-to-https
Updating app links to https. 
Tested locally with mup-web repo using "meetup-web-components": "8.0.3035-beta" dependency,
=> 5258 Updated links in AppBadges component

src/navigation/Nav.jsx
Fix bug with boolean value instead of Function
=> fix bug with boolean value instead of Function

src/navigation/Nav.jsx
The influence of fix is more significant, due to multiple usage of functionality with mixed type.
=> Revert previous fix

src/navigation/Nav.jsx, src/navigation/components/profile/ProfileDropdown.jsx, src/navigation/nav.story.jsx
=> CLUBHOUSE-10370: new navs order

assets/css/main.css, assets/scss/components/_accordion.scss, assets/scss/components/_all.scss, assets/scss/components/_lockedBadge.scss, src/forms/LockedBadge.jsx, src/forms/LockedBadge.story.jsx, src/forms/LockedBadge.test.jsx, src/forms/__snapshots__/LockedBadge.test.jsx.snap, src/interactive/AccordionPanel.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/accordionPanel.test.jsx
This PR moves Locked Badge to separate component
Story details: https://app.clubhouse.io/meetup/story/19500
=> Add `Registration form` form toggles but grey them out with CTA to go PRO (event scheduler)

assets/css/main.css, assets/scss/components/_accordion.scss, assets/scss/components/_lockedBadge.scss, src/interactive/AccordionPanel.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap
This PR fixes LockedBadge flex position
Story details: https://app.clubhouse.io/meetup/story/19500
=> Fix LockedBadge styles

assets/css/main.css, assets/scss/components/_accordion.scss, assets/scss/components/_lockedBadge.scss
This PR removes margin-left from LockedBadge component
Story details: https://app.clubhouse.io/meetup/story/19500
=> Remove margin from LockedBadge component

src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap
https://app.clubhouse.io/meetup/story/20585/upgrade-to-pro-button-isn-t-clickable-in-mobile-view-on-group-page
=> [CH-20585] Fix navigation search bar appearence

assets/css/main.css, assets/css/tailwind.min.css, assets/scss/components/_navbar.scss, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/nav.story.jsx
Story details: https://app.shortcut.com/meetup/story/53525
Unread messages and chevron padding fix.
=> chore: [sc-53525] [FE] Create header for Pro-web

assets/css/main.css, assets/scss/components/_navbar.scss, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/nav.story.jsx
Story details: https://app.shortcut.com/meetup/story/53635
Before:
After:
=> chore: [sc-53635] [FE] Create header for mup-web

src/navigation/Nav.jsx
Story details: https://app.shortcut.com/meetup/story/54090
Fix grey line at the start page.
=> fix: [sc-54090] [Bug]Remove grey line in the header on Group Start Flow]

src/navigation/Nav.jsx, src/navigation/components/NavItem.jsx
Story details: https://app.shortcut.com/meetup/story/53636
Add link click handler for GA tracking.
=> chore: [sc-53636] [FE] GA tracking

src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/nav.story.jsx
Story details: https://app.shortcut.com/meetup/story/53637
'pro-easy-create-group' ff cleanup.
=> chore: [sc-53637] [FE] Cleanup

src/Footer.jsx
Added optional onLinkClick prop to Footer - createMeetup
This PR adds optional `onLinkClick` prop to Footer - createMeetup
=> Added optional onLinkClick prop to Footer - createMeetup

src/__snapshots__/footer.test.jsx.snap, src/navigation/Nav.jsx
[Shortcut](https://app.shortcut.com/meetup/story/66152/fe-desktop-update-core-nav-bar)
=> Update Core nav bar

src/__snapshots__/footer.test.jsx.snap, src/navigation/Nav.jsx
Styling edit
[Shortcut](https://app.shortcut.com/meetup/story/66152/fe-desktop-update-core-nav-bar)
=> Feature/sc 66152/fe desktop update core nav bar

assets/css/main.css, assets/css/tailwind.min.css, src/navigation/Nav.jsx, src/navigation/nav.story.jsx
Story details: https://app.shortcut.com/meetup/story/66738
Screenshot
Before
After
=> Add Pro Button in Core nav bar

src/navigation/Nav.jsx, src/navigation/components/NavItem.jsx
[Shortcut](https://app.shortcut.com/meetup/story/66738/fe-desktop-add-pro-button-in-core-nav-bar)
To fix- 
"Expected : Click on the Pro button should open a page with Pro Landing Page in a new tab (act the same as pro banner)
Actual: Click on the Pro button opens the page with Pro Landing Page in the same tab."
=> add _blank to LinkItem

assets/css/main.css, assets/css/tailwind.min.css, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap, src/navigation/nav.story.jsx
Story details: https://app.shortcut.com/meetup/story/66742
Header cleanup.
=> chore: [sc-66742] [FE] Cleanup [mup-web]

src/interactive/InfoToggle.jsx, src/interactive/Tooltip.jsx, src/interactive/__snapshots__/tooltip.test.jsx.snap
Story details: https://app.shortcut.com/meetup/story/70870
Fix accessibility issues.
=> feat: [sc-70870] Pro Admin (name/role/value)

src/interactive/AccordionPanel.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap, src/navigation/components/NavItem.jsx, src/navigation/components/search/NavbarSearch.jsx
Story details: https://app.shortcut.com/meetup/story/70871
=> feat: [sc-70871] Event create (name/role/value)

src/navigation/Nav.jsx, src/navigation/components/NavItem.jsx
Add ability to pass arbitrary attributes in order to support internal tracking
=> Sc 73441/add ability to pass attributes

src/interactive/AccordionPanel.jsx, src/interactive/AccordionPanelGroup.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap, src/interactive/accordionPanel.test.jsx
=> Feature/sc 73278/event create custom controls aria roles used

src/interactive/Tooltip.jsx, src/interactive/__snapshots__/tooltip.test.jsx.snap
=> [73271] - update accessibility issue

assets/css/main.css, assets/scss/components/_calendar.scss
=> Calendar, contrast issues

assets/css/main.css, assets/scss/components/_all.scss, assets/scss/components/_checkbox.scss, assets/scss/components/_forms.scss, assets/scss/components/_radio.scss, assets/scss/util/_color-mappings.scss, src/forms/Checkbox.jsx, src/forms/RadioButton.jsx, src/forms/__snapshots__/checkbox.test.jsx.snap, src/forms/__snapshots__/radioButton.test.jsx.snap, src/forms/radioButton.story.jsx, src/forms/radioButtonGroup.story.jsx
Partially replaced some checkbox style to web components from swarm
Copied and recreate radio button component form swarm
for test use `8.1.173-beta` version  ❗ ❗ ❗
=> style: Event Create Active user interface component [sc-73128]

assets/css/main.css, assets/scss/components/_checkbox.scss
=> [73138] - update checkboxes focus shadow color

src/forms/RadioButton.jsx
=> add aria-labelledby attribute to radio-button label element

assets/css/main.css, src/forms/RadioButton.jsx
=> [73271] - event create custom controls aria toggle radio button

assets/css/main.css, assets/scss/components/_calendar.scss
=> update calendar day hover and focus states according to contrast rules

src/media/AppBadges.jsx, src/media/__snapshots__/appBadges.test.jsx.snap, src/media/appBadges.test.jsx
Story details: https://app.shortcut.com/meetup/story/75331
Check what type of mobile device a member is using, and render the proper download buttons
=> fix(member app): [sc-75331] [WEB]: Member  Purchase screen shows on RSVP web view.

src/media/AppBadges.jsx, src/media/__snapshots__/appBadges.test.jsx.snap, src/media/appBadges.test.jsx
Reverts meetup/meetup-web-components#861
=> Revert "fix(member app): [sc-75331] [WEB]: Member  Purchase screen shows on RSVP web view."

assets/css/main.css, assets/scss/components/_toggleSwitch.scss, src/forms/ToggleSwitch.jsx, src/interactive/__snapshots__/accordionPanel.test.jsx.snap
**Default**
_Before_
_After_
**Active**
_Before_
_After_
=> Fixed contrast issue for the toggle default state

assets/css/main.css, assets/scss/components/_toggleSwitch.scss, src/forms/Select.jsx, src/forms/ToggleSwitch.jsx, src/forms/__snapshots__/select.test.jsx.snap, src/interactive/__snapshots__/accordionPanel.test.jsx.snap, src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap
move  toggle switch and select from swarm to web components for using Icon from web components, some style fix, centered toggle-switch-disc
=> update toggle switch component

assets/css/main.css, assets/css/tailwind.min.css, src/media/AppBadges.jsx, src/media/__snapshots__/appBadges.test.jsx.snap
=> [72005] - add alt text to app download images

src/forms/CalendarComponent.jsx
=> SC-72007: add alt tags for calendar controls

assets/css/main.css, assets/scss/components/_button.scss, assets/scss/util/_color-mappings.scss, assets/scss/util/_vars.scss
=> Moved color definitions to _vars.scss

src/media/AppBadges.jsx, src/media/__snapshots__/appBadges.test.jsx.snap, src/media/appBadges.story.jsx, src/media/appBadges.test.jsx
https://app.shortcut.com/meetup/story/75331/web-member-purchase-screen-shows-on-rsvp-web-view
=> add props to app badges

src/__snapshots__/footer.test.jsx.snap, src/media/AppBadges.jsx, src/media/__snapshots__/appBadges.test.jsx.snap, src/media/appBadges.story.jsx, src/media/appBadges.test.jsx
https://app.shortcut.com/meetup/story/75331/web-member-purchase-screen-shows-on-rsvp-web-view
=> have component handle conditions

src/interactive/AccordionPanelGroup.jsx, src/interactive/__snapshots__/accordionPanelGroup.test.jsx.snap
Fixed role issues for AccordionPanel
=> Fixed role issues for `AccordionPanel`

src/forms/Textarea.jsx, src/forms/__snapshots__/textarea.test.jsx.snap
Removed conditional rendering of label  from `Textarea`
=> Removed conditional rendering of label  from Textarea field

assets/css/main.css, assets/css/tailwind.min.css, assets/scss/components/_calendar.scss
=> Calendar widget Function cannot be performed [sc-74796]

src/__snapshots__/footer.test.jsx.snap, src/media/AppBadges.jsx, src/media/__snapshots__/appBadges.test.jsx.snap, src/media/appBadges.story.jsx, src/media/appBadges.test.jsx
Reverts meetup/meetup-web-components#872 to unblock updating of meetup-web-components version on `mup-web`
=> Revert "have component handle conditions"

src/navigation/Nav.jsx, src/navigation/__snapshots__/Nav.test.jsx.snap
https://app.shortcut.com/meetup/story/76961/change-sign-up-cta-to-viridian-button
Adding unique class to Sign up CTA in order to update styles in mup-web
=> [sc-76961]: add sign up Nav class

assets/css/main.css, assets/css/tailwind.min.css, src/interactive/Tooltip.jsx, src/interactive/__snapshots__/tooltip.test.jsx.snap, src/utils/components/FloatingPosition.jsx
add event listener for closing when esc press 
for test use "meetup-web-components": "8.1.251-beta"
=> Event Create Additional content not dismissible [sc-74800]

src/navigation/components/NavItem.jsx, src/navigation/components/__snapshots__/navItems.test.jsx.snap
=> Event Create Nested According to Spec [sc-72013]

assets/css/main.css, assets/scss/components/_button.scss
This PR adds focus state for buttons
=> Added focus state for buttons

src/forms/CalendarComponent.jsx
This pr implements workaround to set selected attribute to the day element in calendar
=> Implemented workaround to set selected attribute to the date in calendar

assets/css/main.css, assets/scss/components/_checkbox.scss, src/forms/Checkbox.jsx, src/forms/__snapshots__/checkbox.test.jsx.snap
Story details: https://app.shortcut.com/meetup/story/73137
Checkbox focus outline.
=> chore: [sc-73137] [Pro Dashboard] Active user interface component (Group checkboxes ) lacks 3 to 1 contrast ratio

assets/css/main.css, assets/scss/components/_avatar.scss
Story details: https://app.shortcut.com/meetup/story/73292
**BEFORE:**
Background:
Icon:
Contrast:
**AFTER:**
Background the same.
Icon:
Contrast:
=> chore: [sc-73292] [Group Home] An icon lacks 3 to 1 contrast ratio

src/forms/Checkbox.jsx, src/forms/__snapshots__/checkbox.test.jsx.snap
=> Pro Dashboard Form elements must have labels [sc-74561]

src/interactive/Dropdown.jsx
=> Pro Dashboard Nested According to Spec [sc-74569]

src/forms/Checkbox.jsx
=> Pro Dashboard Programmatic label does not [sc-74049]
